import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'ar' | 'fr';
type ThemeMode = 'light' | 'dark';

type TranslationParams = Record<string, string | number>;

interface AppPreferencesContextType {
    language: Language;
    theme: ThemeMode;
    isRtl: boolean;
    setLanguage: (language: Language) => void;
    toggleLanguage: () => void;
    toggleTheme: () => void;
    t: (key: string, params?: TranslationParams) => string;
}

const translations: Record<Language, Record<string, string>> = {
    ar: {
        'nav.title': 'السجل الإلكتروني لتلقيح الطفل',
        'nav.subtitle': 'منصة رقمية لتدبير وتتبع تلقيح الطفل',
        'nav.mainAriaLabel': 'التنقل الرئيسي',
        'nav.home': 'الرئيسية',
        'nav.children': 'الأطفال',
        'nav.appointments': 'المواعيد',
        'nav.vaccines': 'اللقاحات',
        'nav.profile': 'الملف الشخصي',
        'nav.admin': 'الإدارة',
        'nav.healthCenter': 'المركز الصحي',
        'nav.logout': 'تسجيل الخروج',
        'nav.welcomeUser': 'مرحباً، {{name}}',
        'nav.register': 'إنشاء حساب',
        'nav.login': 'تسجيل الدخول',
        'nav.notifications': 'الإشعارات',
        'nav.noNotifications': 'لا توجد إشعارات حالياً.',
        'nav.notificationOverdue': 'موعد متأخر للطفل {{name}}',
        'nav.notificationToday': 'لديك موعد اليوم للطفل {{name}}',
        'nav.notificationUpcoming': 'موعد قادم للطفل {{name}}',
        'nav.notificationDoseCompleted': 'تم حقن {{dose}} للطفل {{name}} بتاريخ {{date}}',
        'nav.languageToggle': 'FR',
        'nav.themeToggleLight': 'الوضع الفاتح',
        'nav.themeToggleDark': 'الوضع الداكن',
        'common.close': 'إغلاق',
        'common.cancel': 'إلغاء',
        'common.edit': 'تعديل',
        'common.delete': 'حذف',
        'footer.text': 'السجل الإلكتروني لتلقيح الطفل — البرنامج الوطني للتمنيع.',
        'sidebar.dashboard': 'لوحة المتابعة',
        'sidebar.manageChildren': 'إدارة الأطفال',
        'sidebar.vaccineSchedule': 'جدول اللقاحات',
        'role.citizen': 'مواطن',
        'role.health-center': 'مركز صحي',
        'role.admin': 'إدارة',
        'home.logoAlt': 'شعار المنصة',
        'home.eyebrow': 'البرنامج الوطني للتمنيع',
        'home.title': 'واجهة واضحة لإدارة تلقيح الأطفال والمواعيد من المتصفح مباشرة',
        'home.text': 'هذه النسخة تقدم واجهة ويب منظمة لعرض بيانات الأطفال، متابعة الجرعات، وتنظيم المواعيد في مكان واحد.',
        'home.createAccount': 'إنشاء حساب',
        'home.login': 'دخول المستخدم',
        'home.statsLabel': 'مؤشرات البرنامج',
        'home.stat1Label': 'جرعة في البرنامج الوطني للتمنيع',
        'home.stat2Label': 'مرض تقيها اللقاحات',
        'home.stat3Label': 'مجاني في المراكز الصحية',
        'home.statChildren': 'الأطفال المسجلون',
        'home.statRelance': 'جرعات متأخرة أو في المتابعة',
        'home.whyEyebrow': 'لماذا التلقيح؟',
        'home.whyTitle': 'حماية طفلك تبدأ من اللقاح',
        'home.whySubtitle': 'التلقيح هو أكثر تدخلات الصحة العامة فعالية وأماناً لحماية الأطفال من الأمراض الخطيرة',
        'home.why1Title': 'حماية شخصية',
        'home.why1Text': 'يُحصِّن اللقاح جهاز المناعة ويجعله يتعرف على الفيروسات والبكتيريا قبل الإصابة الفعلية.',
        'home.why2Title': 'مناعة المجتمع',
        'home.why2Text': 'كلما ارتفعت نسبة التلقيح في المجتمع، كلما قلّت فرص انتشار الأوبئة وحُميت الفئات الهشة.',
        'home.why3Title': 'وقاية مدى الحياة',
        'home.why3Text': 'بعض اللقاحات تمنح مناعة تدوم سنوات طويلة أو مدى الحياة ضد أمراض خطيرة كالشلل والسل.',
        'home.why4Title': 'مجاني ومتاح للجميع',
        'home.why4Text': 'جميع لقاحات البرنامج الوطني للتمنيع مجانية وتُقدَّم في المراكز الصحية في جميع أنحاء المغرب.',
        'home.tipsEyebrow': 'نصائح للآباء',
        'home.tipsTitle': 'نصائح قبل وبعد التلقيح',
        'home.tip1Title': 'أحضر دفتر التلقيح',
        'home.tip1Text': 'احرص على إحضار دفتر التلقيح في كل زيارة حتى يتم تسجيل الجرعات ومواعيد التذكير بدقة.',
        'home.tip2Title': 'احترم المواعيد',
        'home.tip2Text': 'الالتزام بتاريخ الجرعة يساعد على حماية الطفل في الوقت المناسب ويقلل من التأخير واللحاق.',
        'home.tip3Title': 'راقب الأعراض البسيطة',
        'home.tip3Text': 'قد تظهر حمى خفيفة أو ألم بسيط في موضع الحقن، وغالباً تختفي تلقائياً خلال وقت قصير.',
        'home.tip4Title': 'لا تؤجل دون استشارة',
        'home.tip4Text': 'إذا كان الطفل مريضاً أو لديك تردد بشأن الجرعة، استشر المهني الصحي قبل تأجيل الموعد.',
        'home.tip5Title': 'توجه إلى المركز الصحي',
        'home.tip5Text': 'لقاحات البرنامج الوطني متوفرة مجاناً في المراكز الصحية، ويمكن الحصول على التوجيه من الطاقم الصحي.',
        'home.tip6Title': 'تابع الجرعات القادمة',
        'home.tip6Text': 'استخدم التطبيق لمعرفة المواعيد المفترضة القادمة وتجنب نسيان أي جرعة مهمة.',
        'home.sectionIntro': 'أهم المسارات المتاحة داخل التطبيق',
        'home.openAdmin': 'فتح لوحة الإدارة',
        'home.openHealthCenter': 'فتح لوحة المركز الصحي',
        'home.openDashboard': 'فتح لوحتي',
        'home.cardAuthTitle': 'تسجيل ومصادقة المستخدم',
        'home.cardAuthText': 'إنشاء حساب وربطه ببطاقة التعريف الوطنية ثم الدخول الآمن إلى النظام.',
        'home.cardChildrenTitle': 'إدارة الأطفال',
        'home.cardChildrenText': 'إضافة بيانات الأطفال ومراجعتها مع الوصول السريع إلى سجل التلقيح.',
        'home.cardScheduleTitle': 'جدولة الجرعات',
        'home.cardScheduleText': 'عرض جدول اللقاحات ومتابعة المواعيد القادمة والزيارات السابقة.',
        'home.accountsEyebrow': 'أنواع الحسابات',
        'home.accountsTitle': 'منصة واحدة بثلاثة أدوار واضحة',
        'home.accountsSubtitle': 'التسجيل العمومي مخصص للمواطن فقط، بينما حسابات المركز الصحي والإدارة ينشئها الأدمن.',
        'home.account.citizen.badge': 'للمواطنين',
        'home.account.citizen.title': 'حساب المواطن',
        'home.account.citizen.text': 'تسجيل ذاتي من الواجهة العامة لمتابعة الأطفال، الجرعات، والمواعيد الشخصية.',
        'home.account.healthCenter.badge': 'للأطر الصحية',
        'home.account.healthCenter.title': 'حساب المركز الصحي',
        'home.account.healthCenter.text': 'يمنح لوحة مهنية لمتابعة حالات relance والمواعيد المتأخرة دون صلاحيات إدارة الحسابات.',
        'home.account.admin.badge': 'للإدارة',
        'home.account.admin.title': 'حساب الإدارة',
        'home.account.admin.text': 'يتكفل بإنشاء حسابات المركز الصحي والإدارة وإدارة المستخدمين والمنصة كاملة.',
        'home.pniCalEyebrow': 'الجدول المرجعي',
        'home.pniCalTitle': 'الجدول الوطني لمواعيد الجرعات',
        'home.pniCalSubtitle': 'ملخص سريع لأعمار إعطاء الجرعات الأساسية والمعززة حسب البرنامج الوطني للتمنيع.',
        'home.pniColAge': 'العمر',
        'home.pniColVaccines': 'اللقاحات المبرمجة',
        'home.ageBirth': 'الولادة',
        'home.age4Weeks': '4 أسابيع',
        'home.age8Weeks': '8 أسابيع',
        'home.age10Weeks': '10 أسابيع',
        'home.age12Weeks': '12 أسبوعاً',
        'home.age16Weeks': '16 أسبوعاً',
        'home.age18Weeks': '18 أسبوعاً',
        'home.age9Months': '9 أشهر',
        'home.age12Months': '12 شهراً',
        'home.age18Months': '18 شهراً',
        'home.age5Years': '5 سنوات',
        'home.age11Years': '11 سنة',
        'home.prevTip': 'السابق',
        'home.nextTip': 'التالي',
        'home.tipNumber': 'النصيحة {{index}}',
        'home.vaccinesEyebrow': 'دليل اللقاحات',
        'home.vaccinesTitle': 'تعرف على كل لقاح',
        'home.vaccinesSubtitle': 'معلومات تفصيلية عن كل مستضد في البرنامج الوطني للتمنيع: ما يقيه، طريقة الحقن، الأعراض الجانبية',
        'home.vaccineDisease': 'يقي من',
        'home.vaccineRoute': 'طريقة الحقن',
        'home.vaccineDoses': 'عدد الجرعات',
        'home.vaccineAge': 'عمر التطبيق',
        'home.vaccineSideEffects': 'الأعراض الجانبية الشائعة',
        'home.bcgDisease': 'مرض السل والتهاب السحايا السلي',
        'home.bcgRoute': 'داخل الأدمة (ID) في الذراع الأيمن',
        'home.bcgDoses': 'جرعة واحدة خلال أول 4 أسابيع بعد الولادة',
        'home.bcgAge': 'خلال أول 4 أسابيع بعد الولادة',
        'home.bcgSideEffects': 'بثرة صغيرة تظهر بعد 2-4 أسابيع وتختفي تلقائياً، تاركة أثراً خفيفاً',
        'home.vpoDisease': 'شلل الأطفال (Poliomyélite)',
        'home.vpoRoute': 'فموي (قطرات في الفم)',
        'home.vpoDoses': '6 جرعات (VPO0 إلى VPO5)',
        'home.vpoAge': 'خلال أول 4 أسابيع، 8 أسابيع، 12 أسبوعاً، 16 أسبوعاً، 18 شهراً، 5 سنوات',
        'home.vpoSideEffects': 'نادراً حمى خفيفة أو إسهال عابر، آمن جداً',
        'home.pentaDisease': 'الدفتيريا، الكزاز، السعال الديكي، الهيموفيلوس، التهاب الكبد B',
        'home.pentaRoute': 'حقن عضلي (IM) في الفخذ',
        'home.pentaDoses': '3 جرعات (Penta1، Penta2، Penta3)',
        'home.pentaAge': '8 أسابيع، 12 أسبوعاً، 16 أسبوعاً',
        'home.pentaSideEffects': 'احمرار وتورم خفيف في موضع الحقن، حمى خفيفة لـ 24-48 ساعة',
        'home.pneumoDisease': 'الالتهاب الرئوي والتهاب السحايا البكتيري',
        'home.pneumoRoute': 'حقن عضلي (IM)',
        'home.pneumoDoses': '4 جرعات (PCV1 إلى PCV4)',
        'home.pneumoAge': '10 أسابيع، 16 أسبوعاً، 18 أسبوعاً، 12 شهراً',
        'home.pneumoSideEffects': 'حمى طفيفة، تهيج محلي، نادراً فقدان مؤقت للشهية',
        'home.rotaDisease': 'التهاب المعدة والأمعاء بفيروس الروتا',
        'home.rotaRoute': 'فموي (سائل في الفم)',
        'home.rotaDoses': '3 جرعات (Rota1، Rota2، Rota3)',
        'home.rotaAge': '8 أسابيع، 12 أسبوعاً، 16 أسبوعاً',
        'home.rotaSideEffects': 'سيلان طفيف في الأنف، تهيج خفيف، نادراً إسهال عابر',
        'home.rrDisease': 'الحصبة والحصبة الألمانية (Rougeole-Rubéole)',
        'home.rrRoute': 'حقن تحت الجلد (SC) في الذراع',
        'home.rrDoses': 'جرعتان (RR1، RR2)',
        'home.rrAge': '9 أشهر، 18 شهراً',
        'home.rrSideEffects': 'حمى خفيفة وطفح جلدي بسيط بعد 5-12 يوماً، يختفي تلقائياً',
        'home.vpiDisease': 'شلل الأطفال (جرعة معززة حقنية)',
        'home.vpiRoute': 'حقن عضلي (IM) أو تحت الجلد',
        'home.vpiDoses': 'جرعتان (VPI1، VPI2)',
        'home.vpiAge': '12 أسبوعاً، 9 أشهر',
        'home.vpiSideEffects': 'احمرار طفيف في موضع الحقن، يختفي خلال يومين',
        'home.hbDisease': 'التهاب الكبد الفيروسي B',
        'home.hbRoute': 'حقن عضلي (IM)',
        'home.hbDoses': 'جرعة عند الولادة إذا توفرت (HBn) أو خلال أول 4 أسابيع إذا لم تُعط عند الولادة (HB1)',
        'home.hbAge': 'الولادة أو خلال أول 4 أسابيع حسب الحالة',
        'home.hbSideEffects': 'ألم خفيف في موضع الحقن، حمى طفيفة نادراً',
        'home.hpvDisease': 'فيروس الورم الحليمي البشري (سرطان عنق الرحم)',
        'home.hpvRoute': 'حقن عضلي (IM) في الذراع',
        'home.hpvDoses': 'جرعتان (HPV)',
        'home.hpvAge': '11 سنة (للإناث)',
        'home.hpvSideEffects': 'ألم وتورم في موضع الحقن، دوار خفيف، يزول خلال 1-2 يوم',
        'auth.loginTitle': 'تسجيل الدخول',
        'auth.loginIntro': 'أدخل بياناتك للوصول إلى لوحة تتبع التلقيح.',
        'auth.nationalId': 'رقم البطاقة الوطنية',
        'auth.password': 'كلمة المرور',
        'auth.nationalIdPlaceholder': 'مثال: AB123456',
        'auth.passwordPlaceholder': 'أدخل كلمة المرور',
        'auth.loginButton': 'دخول',
        'auth.loginErrorGeneric': 'تعذر تسجيل الدخول. حاول مرة أخرى.',
        'auth.loginServiceUnavailable': 'خدمة تسجيل الدخول غير متاحة حالياً. تأكد من تشغيل الخادم ثم أعد المحاولة.',
        'auth.loginInvalidCredentials': 'تعذر تسجيل الدخول. تحقق من رقم البطاقة الوطنية وكلمة المرور.',
        'auth.registerTitle': 'إنشاء حساب جديد',
        'auth.registerIntro': 'املأ البيانات الأساسية لإنشاء حساب مواطن وربطه بسجل التلقيح.',
        'auth.registerErrorGeneric': 'تعذر إنشاء الحساب. حاول مرة أخرى.',
        'auth.registerRetry': 'تعذر إنشاء الحساب. راجع البيانات ثم أعد المحاولة.',
        'auth.registerServiceUnavailable': 'خدمة التسجيل غير متاحة حالياً. تأكد من تشغيل الخادم ثم أعد المحاولة.',
        'auth.registerExists': 'يوجد حساب مسجل بهذا الرقم الوطني من قبل.',
        'auth.registerServerError': 'حدث خطأ أثناء إنشاء الحساب. أعد المحاولة بعد قليل.',
        'auth.validation.fullNameRequired': 'الاسم الكامل مطلوب.',
        'auth.validation.genderInvalid': 'يرجى اختيار النوع بشكل صحيح.',
        'auth.validation.birthDateInvalid': 'تاريخ الازدياد غير صالح.',
        'auth.validation.nationalIdRequired': 'رقم البطاقة الوطنية مطلوب.',
        'auth.validation.addressRequired': 'العنوان مطلوب.',
        'auth.validation.phoneInvalid': 'رقم الهاتف غير صالح.',
        'auth.validation.passwordShort': 'كلمة المرور يجب أن تتكون من 6 أحرف على الأقل.',
        'auth.citizenOnlyNotice': 'هذا التسجيل مخصص لحسابات المواطنين فقط. حسابات المركز الصحي والإدارة ينشئها الأدمن.',
        'auth.roleCitizenDesc': 'يمكنه إنشاء الحساب بنفسه من هذه الصفحة.',
        'auth.roleHealthCenterDesc': 'يُنشأ من طرف الأدمن للوصول إلى لوحة المتابعة المهنية.',
        'auth.roleAdminDesc': 'يُنشأ من طرف الأدمن لإدارة الحسابات والمنصة.',
        'auth.loginRoleCitizenDesc': 'يتابع الأطفال والجرعات والمواعيد الشخصية.',
        'auth.loginRoleHealthCenterDesc': 'يراقب حالات relance والمواعيد الحرجة.',
        'auth.loginRoleAdminDesc': 'ينشئ الحسابات ويدير المنصة كاملة.',
        'auth.fullName': 'الاسم الكامل',
        'auth.gender': 'النوع',
        'auth.selectGender': 'اختر النوع',
        'auth.dateOfBirth': 'تاريخ الازدياد',
        'auth.address': 'العنوان',
        'auth.phoneNumber': 'رقم الهاتف',
        'auth.registerButton': 'إنشاء الحساب',
        'auth.profileTitle': 'الملف الشخصي',
        'auth.profileLoginRequired': 'يرجى تسجيل الدخول لعرض الملف الشخصي.',
        'auth.saveChanges': 'حفظ التعديلات',
        'children.pageTitle': 'إدارة معلومات الأطفال',
        'children.listTitle': 'الأطفال المسجلون',
        'children.empty': 'لا يوجد أطفال مسجلون.',
        'children.addButton': 'إضافة طفل',
        'children.cancel': 'إلغاء',
        'children.closeModal': 'إغلاق',
        'children.actions': 'إجراءات',
        'children.edit': 'تعديل',
        'children.delete': 'حذف',
        'children.save': 'حفظ',
        'children.deleteConfirm': 'هل تريد حذف معلومات هذا الطفل؟',
        'children.gender': 'النوع',
        'children.birthDate': 'تاريخ الازدياد',
        'children.nationalId': 'رقم البطاقة الوطنية',
        'children.address': 'العنوان',
        'children.phone': 'الهاتف',
        'appointments.pageTitle': 'مواعيد التلقيح',
        'appointments.welcome': 'مرحباً، {{name}}',
        'appointments.calendarTitle': 'مواعيد جرعات الأطفال',
        'appointments.monthView': 'تعرض اللائحة جرعات شهر {{month}}',
        'appointments.dayView': 'تعرض اللائحة جرعات يوم {{day}}',
        'appointments.backToMonth': 'عرض تلقيحات هذا الشهر',
        'appointments.listTitleDefault': 'المواعيد المفترضة والمسجلة',
        'appointments.listTitleDay': 'جرعات يوم {{day}}',
        'appointments.listTitleMonth': 'تلقيحات شهر {{month}}',
        'appointments.emptyDefault': 'لا توجد مواعيد متاحة حالياً.',
        'appointments.emptyDay': 'لا توجد جرعات في هذا اليوم.',
        'appointments.emptyMonth': 'لا توجد جرعات مفترضة أو مسجلة في هذا الشهر.',
        'appointments.loading': 'جار تحميل المواعيد...',
        'appointments.error': 'تعذر تحميل المواعيد: {{error}}',
        'appointments.date': 'تاريخ الموعد',
        'appointments.time': 'الوقت',
        'appointments.vaccine': 'اللقاح',
        'appointments.status': 'الحالة',
        'appointments.type': 'النوع',
        'appointments.note': 'ملاحظة',
        'appointments.notificationDate': 'تاريخ الإشعار',
        'appointments.notificationSent': 'تم الإشعار في',
        'appointments.reminderMessage': 'رسالة التذكير',
        'appointments.attendPrompt': 'يرجى الحضور إلى المركز الصحي في موعد التلقيح.',
        'appointments.alertsTitle': 'إشعارات المواعيد',
        'appointments.typeExpected': 'موعد مفترض',
        'appointments.typeSaved': 'موعد مسجل',
        'appointments.statusOverdue': 'متأخر',
        'appointments.statusToday': 'اليوم',
        'appointments.statusScheduled': 'مبرمج',
        'appointments.fetchErrorShort': 'تعذر تحميل المواعيد.',
        'appointments.createErrorShort': 'تعذر إنشاء الموعد.',
        'appointments.deleteErrorShort': 'تعذر حذف الموعد.',
        'dashboard.appointments': 'مواعيدك',
        'dashboard.alertsTitle': 'تنبيهات حضور التلقيح',
        'dashboard.children': 'أطفالك',
        'appointmentForm.title': 'برمجة موعد',
        'appointmentForm.date': 'التاريخ',
        'appointmentForm.time': 'الوقت',
        'appointmentForm.childId': 'معرف الطفل',
        'appointmentForm.submit': 'حفظ الموعد',
        'appointmentForm.errorCreate': 'تعذر إنشاء الموعد. حاول مرة أخرى.',
        'vaccine.eyebrow': 'Calendrier PNI',
        'vaccine.title': 'لائحة الجرعات مع تاريخ الحقن',
        'vaccine.text': 'هذا الجدول يعتمد على لائحة المستضدات التي زودتني بها وعلى نفس فكرة المواعيد الظاهرة في الصورة. المثال الافتراضي هو طفل مزداد يوم 01/01/1998.',
        'vaccine.selectChild': 'اختيار طفل مسجل',
        'vaccine.manual': 'إدخال يدوي',
        'vaccine.birthDate': 'تاريخ الازدياد',
        'vaccine.selectedSummary': 'الطفل المختار: {{name}}، تاريخ الازدياد: {{date}}',
        'vaccine.manualSummary': 'التاريخ المعتمد للحساب: {{date}}',
        'vaccine.completed': 'جرعات منجزة',
        'vaccine.catchup': 'rattrapage vaccinal',
        'vaccine.pending': 'مواعيد في الانتظار',
        'vaccine.loading': 'جار تحميل الأطفال المسجلين...',
        'vaccine.table.order': 'الترتيب',
        'vaccine.table.age': 'العمر المرجعي',
        'vaccine.table.antigen': 'المستضد',
        'vaccine.table.scheduledDate': 'تاريخ الحقن',
        'vaccine.table.completedDate': 'تاريخ الجرعة المنجزة',
        'vaccine.table.catchup': 'rattrapage vaccinal',
        'vaccine.table.relaunch': 'relance',
        'vaccine.table.note': 'ملاحظة',
        'vaccine.yes': 'نعم',
        'vaccine.no': 'لا',
        'vaccine.notRequired': 'غير مطلوبة',
        'vaccine.inRelaunch': 'في وضعية relance',
        'vaccine.underTracking': 'قيد التتبع',
        'vaccine.healthCenterChildrenError': 'تعذر تحميل لائحة الأطفال الخاصة بالمركز الصحي.',
        'vaccine.loadDoseError': 'تعذر تحميل الجرعات المنجزة من الخادم.',
        'vaccine.saveDoseError': 'تعذر حفظ تاريخ الجرعة في الخادم.',
        'vaccineList.title': 'اللقاحات المتوفرة',
        'vaccineList.recommendedAge': 'العمر الموصى به',
        'children.fetchErrorShort': 'تعذر تحميل بيانات الأطفال.',
        'children.addErrorShort': 'تعذر إضافة الطفل.',
        'children.updateErrorShort': 'تعذر تعديل الطفل.',
        'children.deleteErrorShort': 'تعذر حذف الطفل.',
        'children.fetchChildError': 'تعذر تحميل بيانات الطفل.',
        'children.updateChildInfoError': 'تعذر تحديث معلومات الطفل.',
        'admin.eyebrow': 'الإدارة',
        'admin.title': 'لوحة التحكم الإدارية',
        'admin.description': 'إدارة حسابات المواطنين والمراكز الصحية والإدارة، إضافة الأطفال، والتحكم في المواعيد من مكان واحد.',
        'admin.metric.accounts': 'الحسابات',
        'admin.metric.children': 'الأطفال',
        'admin.metric.appointments': 'المواعيد',
        'admin.metric.audit': 'السجل',
        'admin.loading': 'جاري تحميل بيانات الإدارة...',
        'admin.createUserTitle': 'إنشاء حساب جديد',
        'admin.addChildTitle': 'إضافة طفل لمستخدم',
        'admin.selectUser': 'اختر المستخدم',
        'admin.placeholder.childNationalId': 'رقم تعريف الطفل',
        'admin.placeholder.optionalPassword': 'كلمة مرور جديدة اختيارية',
        'admin.placeholder.optionalNote': 'ملاحظة اختيارية',
        'admin.button.createUser': 'إنشاء الحساب',
        'admin.button.addChild': 'إضافة الطفل',
        'admin.button.deleteChild': 'حذف الطفل',
        'admin.button.deleteAppointment': 'حذف الموعد',
        'admin.relanceTitle': 'لائحة الأطفال في وضعية relance',
        'admin.relanceDescription': 'الأطفال الذين تجاوزوا موعد جرعة واحدة أو أكثر ولم يتم تسجيل إنجازها بعد.',
        'admin.relanceEmpty': 'لا يوجد أطفال في وضعية relance حالياً.',
        'admin.overdueDoses': '{{count}} جرعة غير منجزة',
        'admin.birthDate': 'تاريخ الازدياد',
        'admin.guardian': 'ولي الأمر',
        'admin.referenceDate': 'الموعد المرجعي',
        'admin.searchUserPlaceholder': 'بحث بالاسم أو البطاقة أو الهاتف',
        'admin.searchChildPlaceholder': 'بحث باسم الطفل أو ولي الأمر',
        'admin.filter.allAccounts': 'كل الحسابات',
        'admin.filter.active': 'النشطة',
        'admin.filter.disabled': 'المعطلة',
        'admin.filter.citizens': 'المواطنون',
        'admin.filter.healthCenters': 'المراكز الصحية',
        'admin.filter.administration': 'الإدارة',
        'admin.filter.allAppointments': 'كل المواعيد',
        'admin.filter.allActions': 'كل العمليات',
        'admin.section.accounts': 'الحسابات',
        'admin.section.children': 'الأطفال',
        'admin.section.appointments': 'المواعيد',
        'admin.section.audit': 'سجل العمليات الإدارية',
        'admin.table.name': 'الاسم',
        'admin.table.role': 'الدور',
        'admin.table.status': 'الحالة',
        'admin.table.nationalId': 'البطاقة الوطنية',
        'admin.table.actions': 'إجراءات',
        'admin.table.child': 'الطفل',
        'admin.table.guardian': 'ولي الأمر',
        'admin.table.dateOfBirth': 'تاريخ الازدياد',
        'admin.table.action': 'الإجراء',
        'admin.table.date': 'التاريخ',
        'admin.table.vaccine': 'اللقاح',
        'admin.table.time': 'الوقت',
        'admin.table.actor': 'الفاعل',
        'admin.table.entity': 'الكيان',
        'admin.table.description': 'الوصف',
        'admin.status.active': 'نشط',
        'admin.status.disabled': 'معطل',
        'admin.status.scheduled': 'مبرمج',
        'admin.status.completed': 'منجز',
        'admin.status.overdue': 'متأخر',
        'admin.status.cancelled': 'ملغى',
        'admin.modal.editUserTitle': 'تعديل الحساب',
        'admin.modal.editChildTitle': 'تعديل الطفل',
        'admin.modal.editAppointmentTitle': 'تعديل الموعد',
        'admin.modal.confirmDeleteTitle': 'تأكيد الحذف',
        'admin.modal.confirmDeleteText': 'هل تريد حذف هذا العنصر نهائياً؟',
        'admin.button.confirmDelete': 'تأكيد الحذف',
        'admin.message.createUserSuccess': 'تم إنشاء الحساب بنجاح.',
        'admin.message.createUserError': 'تعذر إنشاء الحساب الإداري.',
        'admin.message.createChildSuccess': 'تمت إضافة الطفل بنجاح.',
        'admin.message.createChildError': 'تعذر إضافة الطفل.',
        'admin.message.userDisabled': 'تم تعطيل الحساب.',
        'admin.message.userEnabled': 'تم تفعيل الحساب.',
        'admin.message.userStatusError': 'تعذر تحديث حالة الحساب.',
        'admin.message.updateUserSuccess': 'تم تعديل الحساب بنجاح.',
        'admin.message.updateUserError': 'تعذر تعديل الحساب.',
        'admin.message.deleteUserSuccess': 'تم حذف الحساب وما يرتبط به.',
        'admin.message.deleteUserError': 'تعذر حذف الحساب.',
        'admin.message.deleteChildSuccess': 'تم حذف الطفل.',
        'admin.message.deleteChildError': 'تعذر حذف الطفل.',
        'admin.message.updateChildSuccess': 'تم تعديل الطفل بنجاح.',
        'admin.message.updateChildError': 'تعذر تعديل الطفل.',
        'admin.message.deleteAppointmentSuccess': 'تم حذف الموعد.',
        'admin.message.deleteAppointmentError': 'تعذر حذف الموعد.',
        'admin.message.updateAppointmentStatusSuccess': 'تم تحديث حالة الموعد.',
        'admin.message.updateAppointmentStatusError': 'تعذر تحديث الموعد.',
        'admin.message.updateAppointmentSuccess': 'تم تعديل الموعد بنجاح.',
        'admin.message.updateAppointmentError': 'تعذر تعديل الموعد.',
        'admin.error.loadUsers': 'تعذر تحميل الحسابات.',
        'admin.error.loadChildren': 'تعذر تحميل الأطفال.',
        'admin.error.loadAppointments': 'تعذر تحميل المواعيد.',
        'admin.error.loadDoses': 'تعذر تحميل الجرعات المنجزة.',
        'admin.error.loadAudit': 'تعذر تحميل سجل العمليات.',
        'admin.auditEntity.user': 'الحسابات',
        'admin.auditEntity.child': 'الأطفال',
        'admin.auditEntity.appointment': 'المواعيد',
        'admin.auditAction.create-user': 'إنشاء حساب',
        'admin.auditAction.update-user': 'تعديل حساب',
        'admin.auditAction.delete-user': 'حذف حساب',
        'admin.auditAction.create-child': 'إضافة طفل',
        'admin.auditAction.update-child': 'تعديل طفل',
        'admin.auditAction.delete-child': 'حذف طفل',
        'admin.auditAction.update-appointment': 'تعديل موعد',
        'admin.auditAction.delete-appointment': 'حذف موعد',
        'admin.auditAction.create-health-center-appointment': 'إنشاء موعد من طرف المركز الصحي',
        'admin.auditAction.update-health-center-appointment': 'تعديل موعد من طرف المركز الصحي',
        'admin.auditAction.notify-health-center-appointment': 'إرسال إشعار من طرف المركز الصحي',
        'healthCenter.eyebrow': 'المركز الصحي',
        'healthCenter.title': 'لوحة المركز الصحي',
        'healthCenter.description': 'اختر الطفل وحدد موعد الحقن فقط، وسيولد النظام تلقائياً الجرعة الأقرب غير المنجزة مع الجرعات الأخرى الموافقة لنفس التاريخ.',
        'healthCenter.metric.children': 'الأطفال',
        'healthCenter.metric.relance': 'relance',
        'healthCenter.metric.todayAppointments': 'مواعيد اليوم',
        'healthCenter.metric.overdueAppointments': 'مواعيد متأخرة',
        'healthCenter.loading': 'جاري تحميل بيانات المركز الصحي...',
        'healthCenter.loadChildrenError': 'تعذر تحميل الأطفال.',
        'healthCenter.loadAppointmentsError': 'تعذر تحميل المواعيد.',
        'healthCenter.loadCompletedDosesError': 'تعذر تحميل الجرعات المنجزة.',
        'healthCenter.loadVaccinesError': 'تعذر تحميل اللقاحات.',
        'healthCenter.schedulerTitle': 'برمجة موعد الحقن',
        'healthCenter.schedulerDescription': 'اختر الطفل، ثم اختر موعد الحقن. الرسالة والجرعات المقترحة ستتولد تلقائياً.',
        'healthCenter.selectChild': 'اختر الطفل',
        'healthCenter.saveEdit': 'حفظ التعديل',
        'healthCenter.saveAppointment': 'حفظ الموعد',
        'healthCenter.suggestedTitle': 'الجرعات المقترحة في هذا الموعد',
        'healthCenter.relanceTitle': 'حالات relance ذات الأولوية',
        'healthCenter.relanceDescription': 'ابحث باسم الطفل أو ولي الأمر ثم اضغط على الطفل ليتم ملء الموعد والرسالة تلقائياً.',
        'healthCenter.searchPlaceholder': 'بحث بالطفل أو ولي الأمر أو الجرعة',
        'healthCenter.nearestDoses': 'الجرعات الأقرب: {{doses}}',
        'healthCenter.noRemainingDoses': 'لا توجد جرعات متبقية',
        'healthCenter.relanceEmpty': 'لا توجد حالات relance مطابقة حالياً.',
        'healthCenter.overdueDoses': '{{count}} جرعات متأخرة',
        'healthCenter.birthDate': 'تاريخ الازدياد: {{date}}',
        'healthCenter.phone': 'الهاتف: {{phone}}',
        'healthCenter.referenceDate': 'التاريخ المرجعي: {{date}}',
        'healthCenter.clickHint': 'اضغط لاقتراح الجرعات والرسالة تلقائياً',
        'healthCenter.appointmentsTitle': 'المواعيد المبرمجة',
        'healthCenter.appointmentsDescription': 'تعرض اللائحة الجرعة الرئيسية مع الجرعات الأخرى الموافقة لنفس التاريخ داخل خانة الجرعات المبرمجة.',
        'healthCenter.overdueTodayTitle': 'المواعيد المتأخرة أو الخاصة باليوم',
        'healthCenter.table.child': 'الطفل',
        'healthCenter.table.parent': 'ولي الأمر',
        'healthCenter.table.primaryDose': 'الجرعة الرئيسية',
        'healthCenter.table.vaccinationDate': 'تاريخ الحقن',
        'healthCenter.table.plannedDoses': 'الجرعات المبرمجة',
        'healthCenter.table.status': 'الحالة',
        'healthCenter.table.actions': 'الإجراءات',
        'healthCenter.table.date': 'التاريخ',
        'healthCenter.notify': 'إرسال الإشعار',
        'healthCenter.suggestionNotification': 'المرجو الحضور إلى المركز الصحي يوم {{date}} من أجل حقن الجرعات التالية للطفل {{name}}: {{doses}}.',
        'healthCenter.suggestionNotes': 'الجرعات المبرمجة في نفس التاريخ المرجعي {{date}}: {{doses}}.',
        'healthCenter.noPendingNotification': 'لا توجد حالياً جرعات غير منجزة للطفل {{name}}.',
        'healthCenter.noPendingStatus': 'لا توجد جرعات متبقية لهذا الطفل حالياً.',
        'healthCenter.suggestionAuto': 'تم اقتراح الجرعات تلقائياً: {{doses}}.',
        'healthCenter.selectChildError': 'اختر طفلاً لديه جرعات غير منجزة أولاً.',
        'healthCenter.matchVaccinesError': 'تعذر مطابقة الجرعات مع لائحة اللقاحات. أعد تحميل الصفحة ثم حاول مجدداً.',
        'healthCenter.appointmentUpdated': 'تم تعديل موعد الحقن بنجاح.',
        'healthCenter.appointmentSaved': 'تم حفظ موعد الحقن بنجاح.',
        'healthCenter.appointmentSaveError': 'تعذر حفظ موعد الحقن.',
        'healthCenter.defaultReminder': 'المرجو الحضور إلى المركز الصحي بتاريخ {{date}}.',
        'healthCenter.notificationSent': 'تم إرسال الإشعار لولي الأمر.',
        'healthCenter.notificationError': 'تعذر إرسال الإشعار.',
        'gender.male': 'ذكر',
        'gender.female': 'أنثى',
        'gender.other': 'غير محدد'
    },
    fr: {
        'nav.title': 'Registre Electronique de Vaccination de l\'Enfant',
        'nav.subtitle': 'Registre numerique de la vaccination de l\'enfant',
        'nav.mainAriaLabel': 'Navigation principale',
        'nav.home': 'Accueil',
        'nav.children': 'Enfants',
        'nav.appointments': 'Rendez-vous',
        'nav.vaccines': 'Vaccins',
        'nav.profile': 'Profil',
        'nav.admin': 'Administration',
        'nav.healthCenter': 'Centre de sante',
        'nav.logout': 'Déconnexion',
        'nav.welcomeUser': 'Bienvenue, {{name}}',
        'nav.register': 'Créer un compte',
        'nav.login': 'Connexion',
        'nav.notifications': 'Notifications',
        'nav.noNotifications': 'Aucune notification pour le moment.',
        'nav.notificationOverdue': 'Rendez-vous en retard pour {{name}}',
        'nav.notificationToday': "Vous avez un rendez-vous aujourd'hui pour {{name}}",
        'nav.notificationUpcoming': 'Rendez-vous à venir pour {{name}}',
        'nav.notificationDoseCompleted': 'La dose {{dose}} a ete administree a {{name}} le {{date}}',
        'nav.languageToggle': 'AR',
        'nav.themeToggleLight': 'Mode clair',
        'nav.themeToggleDark': 'Mode sombre',
        'common.close': 'Fermer',
        'common.cancel': 'Annuler',
        'common.edit': 'Modifier',
        'common.delete': 'Supprimer',
        'footer.text': 'Registre Electronique de Vaccination de l\'Enfant — Programme National d\'Immunisation.',
        'sidebar.dashboard': 'Tableau de bord',
        'sidebar.manageChildren': 'Gestion des enfants',
        'sidebar.vaccineSchedule': 'Calendrier vaccinal',
        'role.citizen': 'Citoyen',
        'role.health-center': 'Centre de sante',
        'role.admin': 'Administration',
        'home.logoAlt': 'Logo de la plateforme',
        'home.eyebrow': "Programme national d'immunisation",
        'home.title': 'Une interface claire pour gérer la vaccination des enfants et leurs rendez-vous',
        'home.text': "Cette version propose une interface web organisée pour afficher les données des enfants, suivre les doses et organiser les rendez-vous au même endroit.",
        'home.createAccount': 'Créer un compte',
        'home.login': 'Connexion utilisateur',
        'home.statsLabel': "Indicateurs du programme",
        'home.stat1Label': "doses dans le Programme National d'Immunisation",
        'home.stat2Label': 'maladies évitables par la vaccination',
        'home.stat3Label': 'gratuit dans les centres de santé',
        'home.statChildren': 'enfants enregistrés',
        'home.statRelance': 'doses en retard ou à rattraper',
        'home.whyEyebrow': 'Pourquoi vacciner ?',
        'home.whyTitle': 'La protection de votre enfant commence par le vaccin',
        'home.whySubtitle': "La vaccination est l'intervention de santé publique la plus efficace pour protéger les enfants des maladies graves",
        'home.why1Title': 'Protection personnelle',
        'home.why1Text': 'Le vaccin renforce le système immunitaire et lui permet de reconnaître les virus et bactéries avant toute infection réelle.',
        'home.why2Title': 'Immunité collective',
        'home.why2Text': 'Plus le taux de vaccination est élevé, moins les épidémies se propagent et plus les personnes vulnérables sont protégées.',
        'home.why3Title': 'Protection durable',
        'home.why3Text': 'Certains vaccins confèrent une immunité durable, voire à vie, contre des maladies graves comme la polio et la tuberculose.',
        'home.why4Title': 'Gratuit et accessible à tous',
        'home.why4Text': "Tous les vaccins du PNI sont gratuits et disponibles dans les centres de santé partout au Maroc.",
        'home.tipsEyebrow': 'Conseils aux parents',
        'home.tipsTitle': 'Conseils avant et après la vaccination',
        'home.tip1Title': 'Apportez le carnet de vaccination',
        'home.tip1Text': 'Pensez à apporter le carnet à chaque visite afin d’enregistrer précisément les doses et les rappels.',
        'home.tip2Title': 'Respectez les rendez-vous',
        'home.tip2Text': 'Le respect du calendrier vaccinal protège l’enfant au bon moment et limite les retards.',
        'home.tip3Title': 'Surveillez les effets simples',
        'home.tip3Text': 'Une légère fièvre ou une douleur locale peut apparaître après l’injection et disparaît généralement rapidement.',
        'home.tip4Title': 'Ne reportez pas sans avis',
        'home.tip4Text': 'Si l’enfant est malade ou si vous hésitez, demandez conseil au professionnel de santé avant de reporter la dose.',
        'home.tip5Title': 'Rendez-vous au centre de santé',
        'home.tip5Text': 'Les vaccins du programme national sont gratuits dans les centres de santé, où l’équipe peut aussi vous orienter.',
        'home.tip6Title': 'Suivez les prochaines doses',
        'home.tip6Text': 'Utilisez l’application pour voir les rendez-vous attendus et éviter d’oublier une dose importante.',
        'home.sectionIntro': "Principaux parcours disponibles dans l'application",
        'home.openAdmin': 'Ouvrir l administration',
        'home.openHealthCenter': 'Ouvrir le centre de sante',
        'home.openDashboard': 'Ouvrir mon tableau',
        'home.cardAuthTitle': 'Inscription et authentification',
        'home.cardAuthText': 'Créer un compte lié à la carte nationale puis accéder au système en toute sécurité.',
        'home.cardChildrenTitle': 'Gestion des enfants',
        'home.cardChildrenText': 'Ajouter et revoir les données des enfants avec un accès rapide au suivi vaccinal.',
        'home.cardScheduleTitle': 'Planification des doses',
        'home.cardScheduleText': 'Afficher le calendrier vaccinal et suivre les rendez-vous à venir et passés.',
        'home.accountsEyebrow': 'Types de comptes',
        'home.accountsTitle': 'Une seule plateforme avec trois roles clairs',
        'home.accountsSubtitle': 'L inscription publique est reservee au citoyen uniquement, tandis que les comptes centre de sante et administration sont crees par l admin.',
        'home.account.citizen.badge': 'Pour les citoyens',
        'home.account.citizen.title': 'Compte citoyen',
        'home.account.citizen.text': 'Inscription libre depuis l interface publique pour suivre les enfants, les doses et les rendez-vous personnels.',
        'home.account.healthCenter.badge': 'Pour les centres de sante',
        'home.account.healthCenter.title': 'Compte centre de sante',
        'home.account.healthCenter.text': 'Donne un tableau professionnel pour suivre les cas de relance et les rendez-vous en retard sans gerer les comptes.',
        'home.account.admin.badge': 'Pour l administration',
        'home.account.admin.title': 'Compte administration',
        'home.account.admin.text': 'Permet de creer les comptes centre de sante et administration, et de gerer toute la plateforme.',
        'home.pniCalEyebrow': 'Calendrier de référence',
        'home.pniCalTitle': 'Calendrier national des doses',
        'home.pniCalSubtitle': 'Résumé rapide des âges d’administration des doses de base et des rappels selon le programme national.',
        'home.pniColAge': 'Âge',
        'home.pniColVaccines': 'Vaccins programmés',
        'home.ageBirth': 'Naissance',
        'home.age4Weeks': '4 semaines',
        'home.age8Weeks': '8 semaines',
        'home.age10Weeks': '10 semaines',
        'home.age12Weeks': '12 semaines',
        'home.age16Weeks': '16 semaines',
        'home.age18Weeks': '18 semaines',
        'home.age9Months': '9 mois',
        'home.age12Months': '12 mois',
        'home.age18Months': '18 mois',
        'home.age5Years': '5 ans',
        'home.age11Years': '11 ans',
        'home.prevTip': 'Précédent',
        'home.nextTip': 'Suivant',
        'home.tipNumber': 'Conseil {{index}}',
        'home.vaccinesEyebrow': 'Guide des vaccins',
        'home.vaccinesTitle': 'Découvrez chaque vaccin',
        'home.vaccinesSubtitle': "Informations détaillées sur chaque antigène du PNI : protection, mode d'administration, effets secondaires",
        'home.vaccineDisease': 'Protège contre',
        'home.vaccineRoute': "Mode d'administration",
        'home.vaccineDoses': 'Nombre de doses',
        'home.vaccineAge': "Âge d'administration",
        'home.vaccineSideEffects': 'Effets secondaires courants',
        'home.bcgDisease': 'Tuberculose et méningite tuberculeuse',
        'home.bcgRoute': 'Intradermique (ID) dans le bras droit',
        'home.bcgDoses': 'Une seule dose durant les 4 premières semaines après la naissance',
        'home.bcgAge': 'Durant les 4 premières semaines après la naissance',
        'home.bcgSideEffects': 'Petite pustule 2-4 semaines après, disparaît spontanément',
        'home.vpoDisease': 'Poliomyélite (paralysie infantile)',
        'home.vpoRoute': 'Voie orale (gouttes dans la bouche)',
        'home.vpoDoses': '6 doses (VPO0 à VPO5)',
        'home.vpoAge': 'Durant les 4 premières semaines, 8 sem., 12 sem., 16 sem., 18 mois, 5 ans',
        'home.vpoSideEffects': 'Rarement légère fièvre ou diarrhée transitoire, très bien toléré',
        'home.pentaDisease': 'Diphtérie, tétanos, coqueluche, Hib, hépatite B',
        'home.pentaRoute': 'Injection intramusculaire (IM) dans la cuisse',
        'home.pentaDoses': '3 doses (Penta1, Penta2, Penta3)',
        'home.pentaAge': '8 semaines, 12 semaines, 16 semaines',
        'home.pentaSideEffects': "Rougeur et gonflement léger au site d'injection, légère fièvre 24-48h",
        'home.pneumoDisease': 'Pneumonie et méningite bactérienne',
        'home.pneumoRoute': 'Injection intramusculaire (IM)',
        'home.pneumoDoses': '4 doses (PCV1 à PCV4)',
        'home.pneumoAge': '10 sem., 16 sem., 18 sem., 12 mois',
        'home.pneumoSideEffects': "Légère fièvre, irritation locale, perte d'appétit temporaire rare",
        'home.rotaDisease': 'Gastro-entérite à rotavirus',
        'home.rotaRoute': 'Voie orale (liquide dans la bouche)',
        'home.rotaDoses': '3 doses (Rota1, Rota2, Rota3)',
        'home.rotaAge': '8 semaines, 12 semaines, 16 semaines',
        'home.rotaSideEffects': 'Léger écoulement nasal, légère irritation, rarement diarrhée transitoire',
        'home.rrDisease': 'Rougeole et rubéole',
        'home.rrRoute': 'Injection sous-cutanée (SC) dans le bras',
        'home.rrDoses': '2 doses (RR1, RR2)',
        'home.rrAge': '9 mois, 18 mois',
        'home.rrSideEffects': 'Légère fièvre et éruption cutanée bénigne 5-12 jours après, disparaît spontanément',
        'home.vpiDisease': 'Poliomyélite (dose de renforcement injectable)',
        'home.vpiRoute': 'Injection intramusculaire (IM) ou sous-cutanée',
        'home.vpiDoses': '2 doses (VPI1, VPI2)',
        'home.vpiAge': '12 semaines, 9 mois',
        'home.vpiSideEffects': "Légère rougeur au site d'injection, disparaît en deux jours",
        'home.hbDisease': 'Hépatite virale B',
        'home.hbRoute': 'Injection intramusculaire (IM)',
        'home.hbDoses': 'Une dose à la naissance si disponible (HBn) ou durant les 4 premières semaines si elle n’a pas été administrée à la naissance (HB1)',
        'home.hbAge': 'À la naissance ou durant les 4 premières semaines selon le cas',
        'home.hbSideEffects': "Légère douleur au site d'injection, fièvre légère rare",
        'home.hpvDisease': "Papillomavirus humain (cancer du col de l'utérus)",
        'home.hpvRoute': 'Injection intramusculaire (IM) dans le bras',
        'home.hpvDoses': '2 doses (HPV)',
        'home.hpvAge': '11 ans (filles)',
        'home.hpvSideEffects': "Douleur et gonflement au site d'injection, légère sensation de vertige, disparaît en 1-2 jours",
        'auth.loginTitle': 'Connexion',
        'auth.loginIntro': 'Saisissez vos informations pour accéder au suivi vaccinal.',
        'auth.nationalId': 'Numéro de la carte nationale',
        'auth.password': 'Mot de passe',
        'auth.nationalIdPlaceholder': 'Exemple : AB123456',
        'auth.passwordPlaceholder': 'Saisissez le mot de passe',
        'auth.loginButton': 'Se connecter',
        'auth.loginErrorGeneric': 'Impossible de se connecter. Veuillez reessayer.',
        'auth.loginServiceUnavailable': 'Le service de connexion est indisponible pour le moment. Verifiez que le serveur est demarre puis reessayez.',
        'auth.loginInvalidCredentials': 'Impossible de se connecter. Verifiez la carte nationale et le mot de passe.',
        'auth.registerTitle': 'Créer un nouveau compte',
        'auth.registerIntro': 'Renseignez les informations de base pour créer un compte citoyen et le lier au dossier vaccinal.',
        'auth.registerErrorGeneric': 'Impossible de creer le compte. Veuillez reessayer.',
        'auth.registerRetry': 'Impossible de creer le compte. Verifiez les donnees puis reessayez.',
        'auth.registerServiceUnavailable': 'Le service d inscription est indisponible pour le moment. Verifiez que le serveur est demarre puis reessayez.',
        'auth.registerExists': 'Un compte existe deja avec ce numero national.',
        'auth.registerServerError': 'Une erreur est survenue pendant la creation du compte. Reessayez plus tard.',
        'auth.validation.fullNameRequired': 'Le nom complet est obligatoire.',
        'auth.validation.genderInvalid': 'Veuillez choisir un sexe valide.',
        'auth.validation.birthDateInvalid': 'La date de naissance est invalide.',
        'auth.validation.nationalIdRequired': 'Le numero de la carte nationale est obligatoire.',
        'auth.validation.addressRequired': 'L adresse est obligatoire.',
        'auth.validation.phoneInvalid': 'Le numero de telephone est invalide.',
        'auth.validation.passwordShort': 'Le mot de passe doit contenir au moins 6 caracteres.',
        'auth.citizenOnlyNotice': 'Cette inscription est reservee aux comptes citoyens. Les comptes centre de sante et administration sont crees par l administrateur.',
        'auth.roleCitizenDesc': 'Peut creer son compte lui-meme depuis cette page.',
        'auth.roleHealthCenterDesc': 'Cree par l administrateur pour acceder au tableau de suivi professionnel.',
        'auth.roleAdminDesc': 'Cree par l administrateur pour gerer les comptes et la plateforme.',
        'auth.loginRoleCitizenDesc': 'Suit les enfants, les doses et les rendez-vous personnels.',
        'auth.loginRoleHealthCenterDesc': 'Surveille les cas de relance et les rendez-vous critiques.',
        'auth.loginRoleAdminDesc': 'Cree les comptes et gere toute la plateforme.',
        'auth.fullName': 'Nom complet',
        'auth.gender': 'Sexe',
        'auth.selectGender': 'Choisir le sexe',
        'auth.dateOfBirth': 'Date de naissance',
        'auth.address': 'Adresse',
        'auth.phoneNumber': 'Téléphone',
        'auth.registerButton': 'Créer le compte',
        'auth.profileTitle': 'Profil',
        'auth.profileLoginRequired': 'Veuillez vous connecter pour afficher le profil.',
        'auth.saveChanges': 'Enregistrer les modifications',
        'children.pageTitle': 'Gestion des informations des enfants',
        'children.listTitle': 'Enfants enregistrés',
        'children.empty': 'Aucun enfant enregistré.',
        'children.addButton': 'Ajouter un enfant',
        'children.cancel': 'Annuler',
        'children.closeModal': 'Fermer',
        'children.actions': 'Actions',
        'children.edit': 'Modifier',
        'children.delete': 'Supprimer',
        'children.save': 'Enregistrer',
        'children.deleteConfirm': 'Voulez-vous supprimer les informations de cet enfant ?',
        'children.gender': 'Sexe',
        'children.birthDate': 'Date de naissance',
        'children.nationalId': 'Carte nationale',
        'children.address': 'Adresse',
        'children.phone': 'Téléphone',
        'appointments.pageTitle': 'Rendez-vous de vaccination',
        'appointments.welcome': 'Bienvenue, {{name}}',
        'appointments.calendarTitle': 'Rendez-vous des doses des enfants',
        'appointments.monthView': 'La liste affiche les doses du mois {{month}}',
        'appointments.dayView': 'La liste affiche les doses du jour {{day}}',
        'appointments.backToMonth': 'Afficher les vaccinations de ce mois',
        'appointments.listTitleDefault': 'Rendez-vous prévus et enregistrés',
        'appointments.listTitleDay': 'Doses du jour {{day}}',
        'appointments.listTitleMonth': 'Vaccinations du mois {{month}}',
        'appointments.emptyDefault': 'Aucun rendez-vous disponible pour le moment.',
        'appointments.emptyDay': 'Aucune dose pour ce jour.',
        'appointments.emptyMonth': 'Aucune dose prévue ou enregistrée ce mois-ci.',
        'appointments.loading': 'Chargement des rendez-vous...',
        'appointments.error': 'Impossible de charger les rendez-vous : {{error}}',
        'appointments.date': 'Date du rendez-vous',
        'appointments.time': 'Heure',
        'appointments.vaccine': 'Vaccin',
        'appointments.status': 'Statut',
        'appointments.type': 'Type',
        'appointments.note': 'Note',
        'appointments.notificationDate': 'Date de notification',
        'appointments.notificationSent': 'Notification envoyee le',
        'appointments.reminderMessage': 'Message de rappel',
        'appointments.attendPrompt': 'Merci de vous presenter au centre de sante a la date du rendez-vous.',
        'appointments.alertsTitle': 'Notifications de rendez-vous',
        'appointments.typeExpected': 'Rendez-vous prévu',
        'appointments.typeSaved': 'Rendez-vous enregistré',
        'appointments.statusOverdue': 'En retard',
        'appointments.statusToday': "Aujourd'hui",
        'appointments.statusScheduled': 'Planifié',
        'appointments.fetchErrorShort': 'Impossible de charger les rendez-vous.',
        'appointments.createErrorShort': 'Impossible de creer le rendez-vous.',
        'appointments.deleteErrorShort': 'Impossible de supprimer le rendez-vous.',
        'dashboard.appointments': 'Vos rendez-vous',
        'dashboard.alertsTitle': 'Alertes de vaccination',
        'dashboard.children': 'Vos enfants',
        'appointmentForm.title': 'Programmer un rendez-vous',
        'appointmentForm.date': 'Date',
        'appointmentForm.time': 'Heure',
        'appointmentForm.childId': 'Identifiant de l enfant',
        'appointmentForm.submit': 'Enregistrer le rendez-vous',
        'appointmentForm.errorCreate': 'Impossible de creer le rendez-vous. Veuillez reessayer.',
        'vaccine.eyebrow': 'Calendrier PNI',
        'vaccine.title': 'Liste des doses et dates prévues',
        'vaccine.text': "Ce tableau suit la liste des antigènes fournie et la logique des dates visible sur votre image. L'exemple par défaut correspond à un enfant né le 01/01/1998.",
        'vaccine.selectChild': 'Choisir un enfant enregistré',
        'vaccine.manual': 'Saisie manuelle',
        'vaccine.birthDate': 'Date de naissance',
        'vaccine.selectedSummary': 'Enfant sélectionné : {{name}}, date de naissance : {{date}}',
        'vaccine.manualSummary': 'Date utilisée pour le calcul : {{date}}',
        'vaccine.completed': 'Doses réalisées',
        'vaccine.catchup': 'Rattrapage vaccinal',
        'vaccine.pending': 'Rendez-vous en attente',
        'vaccine.loading': 'Chargement des enfants enregistrés...',
        'vaccine.table.order': 'Ordre',
        'vaccine.table.age': 'Âge de référence',
        'vaccine.table.antigen': 'Antigène',
        'vaccine.table.scheduledDate': 'Date prévue',
        'vaccine.table.completedDate': 'Date de dose réalisée',
        'vaccine.table.catchup': 'Rattrapage vaccinal',
        'vaccine.table.relaunch': 'Relance',
        'vaccine.table.note': 'Note',
        'vaccine.yes': 'Oui',
        'vaccine.no': 'Non',
        'vaccine.notRequired': 'Non requise',
        'vaccine.inRelaunch': 'En situation de relance',
        'vaccine.underTracking': 'En suivi',
        'vaccine.healthCenterChildrenError': 'Impossible de charger la liste des enfants du centre de sante.',
        'vaccine.loadDoseError': 'Impossible de charger les doses realisees depuis le serveur.',
        'vaccine.saveDoseError': 'Impossible d enregistrer la date de dose sur le serveur.',
        'vaccineList.title': 'Vaccins disponibles',
        'vaccineList.recommendedAge': 'Age recommande',
        'children.fetchErrorShort': 'Impossible de charger les donnees des enfants.',
        'children.addErrorShort': 'Impossible d ajouter l enfant.',
        'children.updateErrorShort': 'Impossible de modifier l enfant.',
        'children.deleteErrorShort': 'Impossible de supprimer l enfant.',
        'children.fetchChildError': 'Impossible de charger les donnees de l enfant.',
        'children.updateChildInfoError': 'Impossible de mettre a jour les informations de l enfant.',
        'admin.eyebrow': 'Administration',
        'admin.title': 'Tableau de bord administratif',
        'admin.description': 'Gerer les comptes citoyens, centres de sante et administration, ajouter des enfants et controler les rendez-vous depuis un seul endroit.',
        'admin.metric.accounts': 'Comptes',
        'admin.metric.children': 'Enfants',
        'admin.metric.appointments': 'Rendez-vous',
        'admin.metric.audit': 'Journal',
        'admin.loading': 'Chargement des donnees administratives...',
        'admin.createUserTitle': 'Creer un nouveau compte',
        'admin.addChildTitle': 'Ajouter un enfant a un utilisateur',
        'admin.selectUser': 'Choisir l utilisateur',
        'admin.placeholder.childNationalId': 'Identifiant de l enfant',
        'admin.placeholder.optionalPassword': 'Nouveau mot de passe optionnel',
        'admin.placeholder.optionalNote': 'Note facultative',
        'admin.button.createUser': 'Creer le compte',
        'admin.button.addChild': 'Ajouter l enfant',
        'admin.button.deleteChild': 'Supprimer l enfant',
        'admin.button.deleteAppointment': 'Supprimer le rendez-vous',
        'admin.relanceTitle': 'Liste des enfants en situation de relance',
        'admin.relanceDescription': 'Enfants ayant depasse une ou plusieurs doses sans enregistrement de realisation.',
        'admin.relanceEmpty': 'Aucun enfant en situation de relance pour le moment.',
        'admin.overdueDoses': '{{count}} dose(s) non realisee(s)',
        'admin.birthDate': 'Date de naissance',
        'admin.guardian': 'Parent',
        'admin.referenceDate': 'Date de reference',
        'admin.searchUserPlaceholder': 'Recherche par nom, carte ou telephone',
        'admin.searchChildPlaceholder': 'Recherche par nom de l enfant ou du parent',
        'admin.filter.allAccounts': 'Tous les comptes',
        'admin.filter.active': 'Actifs',
        'admin.filter.disabled': 'Desactives',
        'admin.filter.citizens': 'Citoyens',
        'admin.filter.healthCenters': 'Centres de sante',
        'admin.filter.administration': 'Administration',
        'admin.filter.allAppointments': 'Tous les rendez-vous',
        'admin.filter.allActions': 'Toutes les operations',
        'admin.section.accounts': 'Comptes',
        'admin.section.children': 'Enfants',
        'admin.section.appointments': 'Rendez-vous',
        'admin.section.audit': 'Journal des operations administratives',
        'admin.table.name': 'Nom',
        'admin.table.role': 'Role',
        'admin.table.status': 'Statut',
        'admin.table.nationalId': 'Carte nationale',
        'admin.table.actions': 'Actions',
        'admin.table.child': 'Enfant',
        'admin.table.guardian': 'Parent',
        'admin.table.dateOfBirth': 'Date de naissance',
        'admin.table.action': 'Action',
        'admin.table.date': 'Date',
        'admin.table.vaccine': 'Vaccin',
        'admin.table.time': 'Heure',
        'admin.table.actor': 'Auteur',
        'admin.table.entity': 'Entite',
        'admin.table.description': 'Description',
        'admin.status.active': 'Actif',
        'admin.status.disabled': 'Desactive',
        'admin.status.scheduled': 'Programme',
        'admin.status.completed': 'Termine',
        'admin.status.overdue': 'En retard',
        'admin.status.cancelled': 'Annule',
        'admin.modal.editUserTitle': 'Modifier le compte',
        'admin.modal.editChildTitle': 'Modifier l enfant',
        'admin.modal.editAppointmentTitle': 'Modifier le rendez-vous',
        'admin.modal.confirmDeleteTitle': 'Confirmer la suppression',
        'admin.modal.confirmDeleteText': 'Voulez-vous supprimer cet element definitivement ?',
        'admin.button.confirmDelete': 'Confirmer la suppression',
        'admin.message.createUserSuccess': 'Le compte a ete cree avec succes.',
        'admin.message.createUserError': 'Impossible de creer le compte administratif.',
        'admin.message.createChildSuccess': 'L enfant a ete ajoute avec succes.',
        'admin.message.createChildError': 'Impossible d ajouter l enfant.',
        'admin.message.userDisabled': 'Le compte a ete desactive.',
        'admin.message.userEnabled': 'Le compte a ete reactive.',
        'admin.message.userStatusError': 'Impossible de mettre a jour le statut du compte.',
        'admin.message.updateUserSuccess': 'Le compte a ete modifie avec succes.',
        'admin.message.updateUserError': 'Impossible de modifier le compte.',
        'admin.message.deleteUserSuccess': 'Le compte et ses donnees liees ont ete supprimes.',
        'admin.message.deleteUserError': 'Impossible de supprimer le compte.',
        'admin.message.deleteChildSuccess': 'L enfant a ete supprime.',
        'admin.message.deleteChildError': 'Impossible de supprimer l enfant.',
        'admin.message.updateChildSuccess': 'L enfant a ete modifie avec succes.',
        'admin.message.updateChildError': 'Impossible de modifier l enfant.',
        'admin.message.deleteAppointmentSuccess': 'Le rendez-vous a ete supprime.',
        'admin.message.deleteAppointmentError': 'Impossible de supprimer le rendez-vous.',
        'admin.message.updateAppointmentStatusSuccess': 'Le statut du rendez-vous a ete mis a jour.',
        'admin.message.updateAppointmentStatusError': 'Impossible de mettre a jour le rendez-vous.',
        'admin.message.updateAppointmentSuccess': 'Le rendez-vous a ete modifie avec succes.',
        'admin.message.updateAppointmentError': 'Impossible de modifier le rendez-vous.',
        'admin.error.loadUsers': 'Impossible de charger les comptes.',
        'admin.error.loadChildren': 'Impossible de charger les enfants.',
        'admin.error.loadAppointments': 'Impossible de charger les rendez-vous.',
        'admin.error.loadDoses': 'Impossible de charger les doses realisees.',
        'admin.error.loadAudit': 'Impossible de charger le journal des operations.',
        'admin.auditEntity.user': 'Comptes',
        'admin.auditEntity.child': 'Enfants',
        'admin.auditEntity.appointment': 'Rendez-vous',
        'admin.auditAction.create-user': 'Creation de compte',
        'admin.auditAction.update-user': 'Modification de compte',
        'admin.auditAction.delete-user': 'Suppression de compte',
        'admin.auditAction.create-child': 'Ajout d enfant',
        'admin.auditAction.update-child': 'Modification d enfant',
        'admin.auditAction.delete-child': 'Suppression d enfant',
        'admin.auditAction.update-appointment': 'Modification de rendez-vous',
        'admin.auditAction.delete-appointment': 'Suppression de rendez-vous',
        'admin.auditAction.create-health-center-appointment': 'Creation d un rendez-vous centre de sante',
        'admin.auditAction.update-health-center-appointment': 'Modification d un rendez-vous centre de sante',
        'admin.auditAction.notify-health-center-appointment': 'Envoi d une notification centre de sante',
        'healthCenter.eyebrow': 'Centre de sante',
        'healthCenter.title': 'Tableau de bord du centre de sante',
        'healthCenter.description': 'Choisissez seulement l enfant et la date du rendez-vous. Le systeme generera automatiquement la dose la plus proche non realisee avec les autres doses de la meme date.',
        'healthCenter.metric.children': 'Enfants',
        'healthCenter.metric.relance': 'Relance',
        'healthCenter.metric.todayAppointments': 'Rendez-vous du jour',
        'healthCenter.metric.overdueAppointments': 'Rendez-vous en retard',
        'healthCenter.loading': 'Chargement des donnees du centre de sante...',
        'healthCenter.loadChildrenError': 'Impossible de charger les enfants.',
        'healthCenter.loadAppointmentsError': 'Impossible de charger les rendez-vous.',
        'healthCenter.loadCompletedDosesError': 'Impossible de charger les doses realisees.',
        'healthCenter.loadVaccinesError': 'Impossible de charger les vaccins.',
        'healthCenter.schedulerTitle': 'Programmer un rendez-vous de vaccination',
        'healthCenter.schedulerDescription': 'Choisissez l enfant puis la date de vaccination. Le message et les doses proposees seront generes automatiquement.',
        'healthCenter.selectChild': 'Choisir un enfant',
        'healthCenter.saveEdit': 'Enregistrer',
        'healthCenter.saveAppointment': 'Enregistrer le rendez-vous',
        'healthCenter.suggestedTitle': 'Doses proposees pour ce rendez-vous',
        'healthCenter.relanceTitle': 'Cas de relance prioritaires',
        'healthCenter.relanceDescription': 'Recherchez par enfant ou parent puis cliquez sur l enfant pour remplir automatiquement le rendez-vous et le message.',
        'healthCenter.searchPlaceholder': 'Recherche enfant, parent ou dose',
        'healthCenter.nearestDoses': 'Doses proches: {{doses}}',
        'healthCenter.noRemainingDoses': 'Aucune dose restante',
        'healthCenter.relanceEmpty': 'Aucun cas de relance correspondant pour le moment.',
        'healthCenter.overdueDoses': '{{count}} doses en retard',
        'healthCenter.birthDate': 'Naissance: {{date}}',
        'healthCenter.phone': 'Telephone: {{phone}}',
        'healthCenter.referenceDate': 'Date theorique: {{date}}',
        'healthCenter.clickHint': 'Cliquer pour proposer automatiquement les doses et le message',
        'healthCenter.appointmentsTitle': 'Rendez-vous planifies',
        'healthCenter.appointmentsDescription': 'La liste affiche la dose principale et les autres doses de la meme date dans la colonne des doses programmees.',
        'healthCenter.overdueTodayTitle': 'Rendez-vous en retard ou du jour',
        'healthCenter.table.child': 'Enfant',
        'healthCenter.table.parent': 'Parent',
        'healthCenter.table.primaryDose': 'Dose principale',
        'healthCenter.table.vaccinationDate': 'Date de vaccination',
        'healthCenter.table.plannedDoses': 'Doses programmees',
        'healthCenter.table.status': 'Statut',
        'healthCenter.table.actions': 'Actions',
        'healthCenter.table.date': 'Date',
        'healthCenter.notify': 'Notifier',
        'healthCenter.suggestionNotification': 'Merci de vous presenter au centre de sante le {{date}} pour les doses suivantes de {{name}}: {{doses}}.',
        'healthCenter.suggestionNotes': 'Doses programmees a la meme date theorique {{date}}: {{doses}}.',
        'healthCenter.noPendingNotification': 'Aucune dose non realisee actuellement pour {{name}}.',
        'healthCenter.noPendingStatus': 'Aucune dose restante pour cet enfant actuellement.',
        'healthCenter.suggestionAuto': 'Les doses ont ete proposees automatiquement: {{doses}}.',
        'healthCenter.selectChildError': 'Choisissez d abord un enfant avec des doses non realisees.',
        'healthCenter.matchVaccinesError': 'Impossible d associer les doses a la liste des vaccins. Rechargez la page puis reessayez.',
        'healthCenter.appointmentUpdated': 'Le rendez-vous a ete mis a jour.',
        'healthCenter.appointmentSaved': 'Le rendez-vous a ete enregistre avec succes.',
        'healthCenter.appointmentSaveError': 'Impossible d enregistrer le rendez-vous.',
        'healthCenter.defaultReminder': 'Merci de vous presenter au centre de sante le {{date}}.',
        'healthCenter.notificationSent': 'La notification a ete envoyee au parent.',
        'healthCenter.notificationError': 'Impossible d envoyer la notification.',
        'gender.male': 'Garçon',
        'gender.female': 'Fille',
        'gender.other': 'Non precise'
    }
};

const AppPreferencesContext = createContext<AppPreferencesContextType | undefined>(undefined);

const formatTranslation = (template: string, params?: TranslationParams) => {
    if (!params) {
        return template;
    }

    return Object.entries(params).reduce((accumulator, [key, value]) => {
        return accumulator.replace(new RegExp(`{{${key}}}`, 'g'), String(value));
    }, template);
};

export const AppPreferencesProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('app-language') as Language) || 'ar');
    const [theme, setTheme] = useState<ThemeMode>(() => (localStorage.getItem('app-theme') as ThemeMode) || 'light');

    useEffect(() => {
        localStorage.setItem('app-language', language);
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.body.dir = language === 'ar' ? 'rtl' : 'ltr';
    }, [language]);

    useEffect(() => {
        localStorage.setItem('app-theme', theme);
        document.body.dataset.theme = theme;
    }, [theme]);

    const value = useMemo<AppPreferencesContextType>(() => ({
        language,
        theme,
        isRtl: language === 'ar',
        setLanguage,
        toggleLanguage: () => setLanguage((currentValue) => (currentValue === 'ar' ? 'fr' : 'ar')),
        toggleTheme: () => setTheme((currentValue) => (currentValue === 'light' ? 'dark' : 'light')),
        t: (key: string, params?: TranslationParams) => {
            const translation = translations[language][key] || key;
            return formatTranslation(translation, params);
        }
    }), [language, theme]);

    return <AppPreferencesContext.Provider value={value}>{children}</AppPreferencesContext.Provider>;
};

export const useAppPreferences = () => {
    const context = useContext(AppPreferencesContext);

    if (!context) {
        throw new Error('useAppPreferences must be used within AppPreferencesProvider');
    }

    return context;
};
