import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

type Language = 'ar' | 'fr';
type ThemeMode = 'light' | 'dark';

type TranslationParams = Record<string, string | number>;

interface AppPreferencesContextType {
    language: Language;
    theme: ThemeMode;
    isRtl: boolean;
    setLanguage: (language: Language) => void;
    toggleLanguage: () => void;
    toggleTheme: () => void;
    t: (key: string, params?: TranslationParams) => string;
}

const translations: Record<Language, Record<string, string>> = {
    ar: {
        'nav.title': 'منصة مواعيد التلقيح',
        'nav.subtitle': 'تتبع مواعيد الأطفال واللقاحات بسهولة',
        'nav.home': 'الرئيسية',
        'nav.children': 'الأطفال',
        'nav.appointments': 'المواعيد',
        'nav.vaccines': 'اللقاحات',
        'nav.profile': 'الملف الشخصي',
        'nav.admin': 'الإدارة',
        'nav.logout': 'تسجيل الخروج',
        'nav.welcomeUser': 'مرحباً، {{name}}',
        'nav.register': 'إنشاء حساب',
        'nav.login': 'تسجيل الدخول',
        'nav.notifications': 'الإشعارات',
        'nav.noNotifications': 'لا توجد إشعارات حالياً.',
        'nav.notificationOverdue': 'موعد متأخر للطفل {{name}}',
        'nav.notificationToday': 'لديك موعد اليوم للطفل {{name}}',
        'nav.notificationUpcoming': 'موعد قادم للطفل {{name}}',
        'nav.languageToggle': 'FR',
        'nav.themeToggleLight': 'الوضع الفاتح',
        'nav.themeToggleDark': 'الوضع الداكن',
        'footer.text': 'منصة مواعيد التلقيح — البرنامج الوطني للتمنيع.',
        'home.logoAlt': 'شعار المنصة',
        'home.eyebrow': 'البرنامج الوطني للتمنيع',
        'home.title': 'واجهة واضحة لإدارة تلقيح الأطفال والمواعيد من المتصفح مباشرة',
        'home.text': 'هذه النسخة تقدم واجهة ويب منظمة لعرض بيانات الأطفال، متابعة الجرعات، وتنظيم المواعيد في مكان واحد.',
        'home.createAccount': 'إنشاء حساب',
        'home.login': 'دخول المستخدم',
        'home.statsLabel': 'مؤشرات البرنامج',
        'home.stat1Label': 'جرعة في البرنامج الوطني للتمنيع',
        'home.stat2Label': 'مرض تقيها اللقاحات',
        'home.stat3Label': 'مجاني في المراكز الصحية',
        'home.statChildren': 'الأطفال المسجلون',
        'home.statRelance': 'جرعات متأخرة أو في المتابعة',
        'home.whyEyebrow': 'لماذا التلقيح؟',
        'home.whyTitle': 'حماية طفلك تبدأ من اللقاح',
        'home.whySubtitle': 'التلقيح هو أكثر تدخلات الصحة العامة فعالية وأماناً لحماية الأطفال من الأمراض الخطيرة',
        'home.why1Title': 'حماية شخصية',
        'home.why1Text': 'يُحصِّن اللقاح جهاز المناعة ويجعله يتعرف على الفيروسات والبكتيريا قبل الإصابة الفعلية.',
        'home.why2Title': 'مناعة المجتمع',
        'home.why2Text': 'كلما ارتفعت نسبة التلقيح في المجتمع، كلما قلّت فرص انتشار الأوبئة وحُميت الفئات الهشة.',
        'home.why3Title': 'وقاية مدى الحياة',
        'home.why3Text': 'بعض اللقاحات تمنح مناعة تدوم سنوات طويلة أو مدى الحياة ضد أمراض خطيرة كالشلل والسل.',
        'home.why4Title': 'مجاني ومتاح للجميع',
        'home.why4Text': 'جميع لقاحات البرنامج الوطني للتمنيع مجانية وتُقدَّم في المراكز الصحية في جميع أنحاء المغرب.',
        'home.tipsEyebrow': 'نصائح للآباء',
        'home.tipsTitle': 'نصائح قبل وبعد التلقيح',
        'home.tip1Title': 'أحضر دفتر التلقيح',
        'home.tip1Text': 'احرص على إحضار دفتر التلقيح في كل زيارة حتى يتم تسجيل الجرعات ومواعيد التذكير بدقة.',
        'home.tip2Title': 'احترم المواعيد',
        'home.tip2Text': 'الالتزام بتاريخ الجرعة يساعد على حماية الطفل في الوقت المناسب ويقلل من التأخير واللحاق.',
        'home.tip3Title': 'راقب الأعراض البسيطة',
        'home.tip3Text': 'قد تظهر حمى خفيفة أو ألم بسيط في موضع الحقن، وغالباً تختفي تلقائياً خلال وقت قصير.',
        'home.tip4Title': 'لا تؤجل دون استشارة',
        'home.tip4Text': 'إذا كان الطفل مريضاً أو لديك تردد بشأن الجرعة، استشر المهني الصحي قبل تأجيل الموعد.',
        'home.tip5Title': 'توجه إلى المركز الصحي',
        'home.tip5Text': 'لقاحات البرنامج الوطني متوفرة مجاناً في المراكز الصحية، ويمكن الحصول على التوجيه من الطاقم الصحي.',
        'home.tip6Title': 'تابع الجرعات القادمة',
        'home.tip6Text': 'استخدم التطبيق لمعرفة المواعيد المفترضة القادمة وتجنب نسيان أي جرعة مهمة.',
        'home.sectionIntro': 'أهم المسارات المتاحة داخل التطبيق',
        'home.cardAuthTitle': 'تسجيل ومصادقة المستخدم',
        'home.cardAuthText': 'إنشاء حساب وربطه ببطاقة التعريف الوطنية ثم الدخول الآمن إلى النظام.',
        'home.cardChildrenTitle': 'إدارة الأطفال',
        'home.cardChildrenText': 'إضافة بيانات الأطفال ومراجعتها مع الوصول السريع إلى سجل التلقيح.',
        'home.cardScheduleTitle': 'جدولة الجرعات',
        'home.cardScheduleText': 'عرض جدول اللقاحات ومتابعة المواعيد القادمة والزيارات السابقة.',
        'home.pniCalEyebrow': 'الجدول المرجعي',
        'home.pniCalTitle': 'الجدول الوطني لمواعيد الجرعات',
        'home.pniCalSubtitle': 'ملخص سريع لأعمار إعطاء الجرعات الأساسية والمعززة حسب البرنامج الوطني للتمنيع.',
        'home.pniColAge': 'العمر',
        'home.pniColVaccines': 'اللقاحات المبرمجة',
        'home.ageBirth': 'الولادة',
        'home.age4Weeks': '4 أسابيع',
        'home.age8Weeks': '8 أسابيع',
        'home.age10Weeks': '10 أسابيع',
        'home.age12Weeks': '12 أسبوعاً',
        'home.age16Weeks': '16 أسبوعاً',
        'home.age18Weeks': '18 أسبوعاً',
        'home.age9Months': '9 أشهر',
        'home.age12Months': '12 شهراً',
        'home.age18Months': '18 شهراً',
        'home.age5Years': '5 سنوات',
        'home.age11Years': '11 سنة',
        'home.prevTip': 'السابق',
        'home.nextTip': 'التالي',
        'home.tipNumber': 'النصيحة {{index}}',
        'home.vaccinesEyebrow': 'دليل اللقاحات',
        'home.vaccinesTitle': 'تعرف على كل لقاح',
        'home.vaccinesSubtitle': 'معلومات تفصيلية عن كل مستضد في البرنامج الوطني للتمنيع: ما يقيه، طريقة الحقن، الأعراض الجانبية',
        'home.vaccineDisease': 'يقي من',
        'home.vaccineRoute': 'طريقة الحقن',
        'home.vaccineDoses': 'عدد الجرعات',
        'home.vaccineAge': 'عمر التطبيق',
        'home.vaccineSideEffects': 'الأعراض الجانبية الشائعة',
        'home.bcgDisease': 'مرض السل والتهاب السحايا السلي',
        'home.bcgRoute': 'داخل الأدمة (ID) في الذراع الأيمن',
        'home.bcgDoses': 'جرعة واحدة خلال أول 4 أسابيع بعد الولادة',
        'home.bcgAge': 'خلال أول 4 أسابيع بعد الولادة',
        'home.bcgSideEffects': 'بثرة صغيرة تظهر بعد 2-4 أسابيع وتختفي تلقائياً، تاركة أثراً خفيفاً',
        'home.vpoDisease': 'شلل الأطفال (Poliomyélite)',
        'home.vpoRoute': 'فموي (قطرات في الفم)',
        'home.vpoDoses': '6 جرعات (VPO0 إلى VPO5)',
        'home.vpoAge': 'خلال أول 4 أسابيع، 8 أسابيع، 12 أسبوعاً، 16 أسبوعاً، 18 شهراً، 5 سنوات',
        'home.vpoSideEffects': 'نادراً حمى خفيفة أو إسهال عابر، آمن جداً',
        'home.pentaDisease': 'الدفتيريا، الكزاز، السعال الديكي، الهيموفيلوس، التهاب الكبد B',
        'home.pentaRoute': 'حقن عضلي (IM) في الفخذ',
        'home.pentaDoses': '3 جرعات (Penta1، Penta2، Penta3)',
        'home.pentaAge': '8 أسابيع، 12 أسبوعاً، 16 أسبوعاً',
        'home.pentaSideEffects': 'احمرار وتورم خفيف في موضع الحقن، حمى خفيفة لـ 24-48 ساعة',
        'home.pneumoDisease': 'الالتهاب الرئوي والتهاب السحايا البكتيري',
        'home.pneumoRoute': 'حقن عضلي (IM)',
        'home.pneumoDoses': '4 جرعات (PCV1 إلى PCV4)',
        'home.pneumoAge': '10 أسابيع، 16 أسبوعاً، 18 أسبوعاً، 12 شهراً',
        'home.pneumoSideEffects': 'حمى طفيفة، تهيج محلي، نادراً فقدان مؤقت للشهية',
        'home.rotaDisease': 'التهاب المعدة والأمعاء بفيروس الروتا',
        'home.rotaRoute': 'فموي (سائل في الفم)',
        'home.rotaDoses': '3 جرعات (Rota1، Rota2، Rota3)',
        'home.rotaAge': '8 أسابيع، 12 أسبوعاً، 16 أسبوعاً',
        'home.rotaSideEffects': 'سيلان طفيف في الأنف، تهيج خفيف، نادراً إسهال عابر',
        'home.rrDisease': 'الحصبة والحصبة الألمانية (Rougeole-Rubéole)',
        'home.rrRoute': 'حقن تحت الجلد (SC) في الذراع',
        'home.rrDoses': 'جرعتان (RR1، RR2)',
        'home.rrAge': '9 أشهر، 18 شهراً',
        'home.rrSideEffects': 'حمى خفيفة وطفح جلدي بسيط بعد 5-12 يوماً، يختفي تلقائياً',
        'home.vpiDisease': 'شلل الأطفال (جرعة معززة حقنية)',
        'home.vpiRoute': 'حقن عضلي (IM) أو تحت الجلد',
        'home.vpiDoses': 'جرعتان (VPI1، VPI2)',
        'home.vpiAge': '12 أسبوعاً، 9 أشهر',
        'home.vpiSideEffects': 'احمرار طفيف في موضع الحقن، يختفي خلال يومين',
        'home.hbDisease': 'التهاب الكبد الفيروسي B',
        'home.hbRoute': 'حقن عضلي (IM)',
        'home.hbDoses': 'جرعة عند الولادة إذا توفرت (HBn) أو خلال أول 4 أسابيع إذا لم تُعط عند الولادة (HB1)',
        'home.hbAge': 'الولادة أو خلال أول 4 أسابيع حسب الحالة',
        'home.hbSideEffects': 'ألم خفيف في موضع الحقن، حمى طفيفة نادراً',
        'home.hpvDisease': 'فيروس الورم الحليمي البشري (سرطان عنق الرحم)',
        'home.hpvRoute': 'حقن عضلي (IM) في الذراع',
        'home.hpvDoses': 'جرعتان (HPV)',
        'home.hpvAge': '11 سنة (للإناث)',
        'home.hpvSideEffects': 'ألم وتورم في موضع الحقن، دوار خفيف، يزول خلال 1-2 يوم',
        'auth.loginTitle': 'تسجيل الدخول',
        'auth.loginIntro': 'أدخل بياناتك للوصول إلى لوحة تتبع التلقيح.',
        'auth.nationalId': 'رقم البطاقة الوطنية',
        'auth.password': 'كلمة المرور',
        'auth.nationalIdPlaceholder': 'مثال: AB123456',
        'auth.passwordPlaceholder': 'أدخل كلمة المرور',
        'auth.loginButton': 'دخول',
        'auth.registerTitle': 'إنشاء حساب جديد',
        'auth.registerIntro': 'املأ البيانات الأساسية لربط ولي الأمر بسجل التلقيح.',
        'auth.fullName': 'الاسم الكامل',
        'auth.gender': 'النوع',
        'auth.selectGender': 'اختر النوع',
        'auth.dateOfBirth': 'تاريخ الازدياد',
        'auth.address': 'العنوان',
        'auth.phoneNumber': 'رقم الهاتف',
        'auth.registerButton': 'إنشاء الحساب',
        'auth.profileTitle': 'الملف الشخصي',
        'auth.profileLoginRequired': 'يرجى تسجيل الدخول لعرض الملف الشخصي.',
        'auth.saveChanges': 'حفظ التعديلات',
        'children.pageTitle': 'إدارة معلومات الأطفال',
        'children.listTitle': 'الأطفال المسجلون',
        'children.empty': 'لا يوجد أطفال مسجلون.',
        'children.addButton': 'إضافة طفل',
        'children.cancel': 'إلغاء',
        'children.closeModal': 'إغلاق',
        'children.actions': 'إجراءات',
        'children.edit': 'تعديل',
        'children.delete': 'حذف',
        'children.save': 'حفظ',
        'children.deleteConfirm': 'هل تريد حذف معلومات هذا الطفل؟',
        'children.gender': 'النوع',
        'children.birthDate': 'تاريخ الازدياد',
        'children.nationalId': 'رقم البطاقة الوطنية',
        'children.address': 'العنوان',
        'children.phone': 'الهاتف',
        'appointments.pageTitle': 'مواعيد التلقيح',
        'appointments.welcome': 'مرحباً، {{name}}',
        'appointments.calendarTitle': 'مواعيد جرعات الأطفال',
        'appointments.monthView': 'تعرض اللائحة جرعات شهر {{month}}',
        'appointments.dayView': 'تعرض اللائحة جرعات يوم {{day}}',
        'appointments.backToMonth': 'عرض تلقيحات هذا الشهر',
        'appointments.listTitleDefault': 'المواعيد المفترضة والمسجلة',
        'appointments.listTitleDay': 'جرعات يوم {{day}}',
        'appointments.listTitleMonth': 'تلقيحات شهر {{month}}',
        'appointments.emptyDefault': 'لا توجد مواعيد متاحة حالياً.',
        'appointments.emptyDay': 'لا توجد جرعات في هذا اليوم.',
        'appointments.emptyMonth': 'لا توجد جرعات مفترضة أو مسجلة في هذا الشهر.',
        'appointments.loading': 'جار تحميل المواعيد...',
        'appointments.error': 'تعذر تحميل المواعيد: {{error}}',
        'appointments.date': 'تاريخ الموعد',
        'appointments.time': 'الوقت',
        'appointments.vaccine': 'اللقاح',
        'appointments.status': 'الحالة',
        'appointments.type': 'النوع',
        'appointments.note': 'ملاحظة',
        'appointments.typeExpected': 'موعد مفترض',
        'appointments.typeSaved': 'موعد مسجل',
        'appointments.statusOverdue': 'متأخر',
        'appointments.statusToday': 'اليوم',
        'appointments.statusScheduled': 'مبرمج',
        'dashboard.appointments': 'مواعيدك',
        'dashboard.children': 'أطفالك',
        'vaccine.eyebrow': 'Calendrier PNI',
        'vaccine.title': 'لائحة الجرعات مع تاريخ الحقن',
        'vaccine.text': 'هذا الجدول يعتمد على لائحة المستضدات التي زودتني بها وعلى نفس فكرة المواعيد الظاهرة في الصورة. المثال الافتراضي هو طفل مزداد يوم 01/01/1998.',
        'vaccine.selectChild': 'اختيار طفل مسجل',
        'vaccine.manual': 'إدخال يدوي',
        'vaccine.birthDate': 'تاريخ الازدياد',
        'vaccine.selectedSummary': 'الطفل المختار: {{name}}، تاريخ الازدياد: {{date}}',
        'vaccine.manualSummary': 'التاريخ المعتمد للحساب: {{date}}',
        'vaccine.completed': 'جرعات منجزة',
        'vaccine.catchup': 'rattrapage vaccinal',
        'vaccine.pending': 'مواعيد في الانتظار',
        'vaccine.loading': 'جار تحميل الأطفال المسجلين...',
        'vaccine.table.order': 'الترتيب',
        'vaccine.table.age': 'العمر المرجعي',
        'vaccine.table.antigen': 'المستضد',
        'vaccine.table.scheduledDate': 'تاريخ الحقن',
        'vaccine.table.completedDate': 'تاريخ الجرعة المنجزة',
        'vaccine.table.catchup': 'rattrapage vaccinal',
        'vaccine.table.relaunch': 'relance',
        'vaccine.table.note': 'ملاحظة',
        'vaccine.yes': 'نعم',
        'vaccine.no': 'لا',
        'vaccine.notRequired': 'غير مطلوبة',
        'vaccine.inRelaunch': 'في وضعية relance',
        'vaccine.underTracking': 'قيد التتبع',
        'gender.male': 'ذكر',
        'gender.female': 'أنثى'
    },
    fr: {
        'nav.title': 'Plateforme des rendez-vous de vaccination',
        'nav.subtitle': 'Suivi simple des enfants et des vaccins',
        'nav.home': 'Accueil',
        'nav.children': 'Enfants',
        'nav.appointments': 'Rendez-vous',
        'nav.vaccines': 'Vaccins',
        'nav.profile': 'Profil',
        'nav.admin': 'Administration',
        'nav.logout': 'Déconnexion',
        'nav.welcomeUser': 'Bienvenue, {{name}}',
        'nav.register': 'Créer un compte',
        'nav.login': 'Connexion',
        'nav.notifications': 'Notifications',
        'nav.noNotifications': 'Aucune notification pour le moment.',
        'nav.notificationOverdue': 'Rendez-vous en retard pour {{name}}',
        'nav.notificationToday': "Vous avez un rendez-vous aujourd'hui pour {{name}}",
        'nav.notificationUpcoming': 'Rendez-vous à venir pour {{name}}',
        'nav.languageToggle': 'AR',
        'nav.themeToggleLight': 'Mode clair',
        'nav.themeToggleDark': 'Mode sombre',
        'footer.text': 'Plateforme des rendez-vous de vaccination — Programme National d\'Immunisation.',
        'home.logoAlt': 'Logo de la plateforme',
        'home.eyebrow': "Programme national d'immunisation",
        'home.title': 'Une interface claire pour gérer la vaccination des enfants et leurs rendez-vous',
        'home.text': "Cette version propose une interface web organisée pour afficher les données des enfants, suivre les doses et organiser les rendez-vous au même endroit.",
        'home.createAccount': 'Créer un compte',
        'home.login': 'Connexion utilisateur',
        'home.statsLabel': "Indicateurs du programme",
        'home.stat1Label': "doses dans le Programme National d'Immunisation",
        'home.stat2Label': 'maladies évitables par la vaccination',
        'home.stat3Label': 'gratuit dans les centres de santé',
        'home.statChildren': 'enfants enregistrés',
        'home.statRelance': 'doses en retard ou à rattraper',
        'home.whyEyebrow': 'Pourquoi vacciner ?',
        'home.whyTitle': 'La protection de votre enfant commence par le vaccin',
        'home.whySubtitle': "La vaccination est l'intervention de santé publique la plus efficace pour protéger les enfants des maladies graves",
        'home.why1Title': 'Protection personnelle',
        'home.why1Text': 'Le vaccin renforce le système immunitaire et lui permet de reconnaître les virus et bactéries avant toute infection réelle.',
        'home.why2Title': 'Immunité collective',
        'home.why2Text': 'Plus le taux de vaccination est élevé, moins les épidémies se propagent et plus les personnes vulnérables sont protégées.',
        'home.why3Title': 'Protection durable',
        'home.why3Text': 'Certains vaccins confèrent une immunité durable, voire à vie, contre des maladies graves comme la polio et la tuberculose.',
        'home.why4Title': 'Gratuit et accessible à tous',
        'home.why4Text': "Tous les vaccins du PNI sont gratuits et disponibles dans les centres de santé partout au Maroc.",
        'home.tipsEyebrow': 'Conseils aux parents',
        'home.tipsTitle': 'Conseils avant et après la vaccination',
        'home.tip1Title': 'Apportez le carnet de vaccination',
        'home.tip1Text': 'Pensez à apporter le carnet à chaque visite afin d’enregistrer précisément les doses et les rappels.',
        'home.tip2Title': 'Respectez les rendez-vous',
        'home.tip2Text': 'Le respect du calendrier vaccinal protège l’enfant au bon moment et limite les retards.',
        'home.tip3Title': 'Surveillez les effets simples',
        'home.tip3Text': 'Une légère fièvre ou une douleur locale peut apparaître après l’injection et disparaît généralement rapidement.',
        'home.tip4Title': 'Ne reportez pas sans avis',
        'home.tip4Text': 'Si l’enfant est malade ou si vous hésitez, demandez conseil au professionnel de santé avant de reporter la dose.',
        'home.tip5Title': 'Rendez-vous au centre de santé',
        'home.tip5Text': 'Les vaccins du programme national sont gratuits dans les centres de santé, où l’équipe peut aussi vous orienter.',
        'home.tip6Title': 'Suivez les prochaines doses',
        'home.tip6Text': 'Utilisez l’application pour voir les rendez-vous attendus et éviter d’oublier une dose importante.',
        'home.sectionIntro': "Principaux parcours disponibles dans l'application",
        'home.cardAuthTitle': 'Inscription et authentification',
        'home.cardAuthText': 'Créer un compte lié à la carte nationale puis accéder au système en toute sécurité.',
        'home.cardChildrenTitle': 'Gestion des enfants',
        'home.cardChildrenText': 'Ajouter et revoir les données des enfants avec un accès rapide au suivi vaccinal.',
        'home.cardScheduleTitle': 'Planification des doses',
        'home.cardScheduleText': 'Afficher le calendrier vaccinal et suivre les rendez-vous à venir et passés.',
        'home.pniCalEyebrow': 'Calendrier de référence',
        'home.pniCalTitle': 'Calendrier national des doses',
        'home.pniCalSubtitle': 'Résumé rapide des âges d’administration des doses de base et des rappels selon le programme national.',
        'home.pniColAge': 'Âge',
        'home.pniColVaccines': 'Vaccins programmés',
        'home.ageBirth': 'Naissance',
        'home.age4Weeks': '4 semaines',
        'home.age8Weeks': '8 semaines',
        'home.age10Weeks': '10 semaines',
        'home.age12Weeks': '12 semaines',
        'home.age16Weeks': '16 semaines',
        'home.age18Weeks': '18 semaines',
        'home.age9Months': '9 mois',
        'home.age12Months': '12 mois',
        'home.age18Months': '18 mois',
        'home.age5Years': '5 ans',
        'home.age11Years': '11 ans',
        'home.prevTip': 'Précédent',
        'home.nextTip': 'Suivant',
        'home.tipNumber': 'Conseil {{index}}',
        'home.vaccinesEyebrow': 'Guide des vaccins',
        'home.vaccinesTitle': 'Découvrez chaque vaccin',
        'home.vaccinesSubtitle': "Informations détaillées sur chaque antigène du PNI : protection, mode d'administration, effets secondaires",
        'home.vaccineDisease': 'Protège contre',
        'home.vaccineRoute': "Mode d'administration",
        'home.vaccineDoses': 'Nombre de doses',
        'home.vaccineAge': "Âge d'administration",
        'home.vaccineSideEffects': 'Effets secondaires courants',
        'home.bcgDisease': 'Tuberculose et méningite tuberculeuse',
        'home.bcgRoute': 'Intradermique (ID) dans le bras droit',
        'home.bcgDoses': 'Une seule dose durant les 4 premières semaines après la naissance',
        'home.bcgAge': 'Durant les 4 premières semaines après la naissance',
        'home.bcgSideEffects': 'Petite pustule 2-4 semaines après, disparaît spontanément',
        'home.vpoDisease': 'Poliomyélite (paralysie infantile)',
        'home.vpoRoute': 'Voie orale (gouttes dans la bouche)',
        'home.vpoDoses': '6 doses (VPO0 à VPO5)',
        'home.vpoAge': 'Durant les 4 premières semaines, 8 sem., 12 sem., 16 sem., 18 mois, 5 ans',
        'home.vpoSideEffects': 'Rarement légère fièvre ou diarrhée transitoire, très bien toléré',
        'home.pentaDisease': 'Diphtérie, tétanos, coqueluche, Hib, hépatite B',
        'home.pentaRoute': 'Injection intramusculaire (IM) dans la cuisse',
        'home.pentaDoses': '3 doses (Penta1, Penta2, Penta3)',
        'home.pentaAge': '8 semaines, 12 semaines, 16 semaines',
        'home.pentaSideEffects': "Rougeur et gonflement léger au site d'injection, légère fièvre 24-48h",
        'home.pneumoDisease': 'Pneumonie et méningite bactérienne',
        'home.pneumoRoute': 'Injection intramusculaire (IM)',
        'home.pneumoDoses': '4 doses (PCV1 à PCV4)',
        'home.pneumoAge': '10 sem., 16 sem., 18 sem., 12 mois',
        'home.pneumoSideEffects': "Légère fièvre, irritation locale, perte d'appétit temporaire rare",
        'home.rotaDisease': 'Gastro-entérite à rotavirus',
        'home.rotaRoute': 'Voie orale (liquide dans la bouche)',
        'home.rotaDoses': '3 doses (Rota1, Rota2, Rota3)',
        'home.rotaAge': '8 semaines, 12 semaines, 16 semaines',
        'home.rotaSideEffects': 'Léger écoulement nasal, légère irritation, rarement diarrhée transitoire',
        'home.rrDisease': 'Rougeole et rubéole',
        'home.rrRoute': 'Injection sous-cutanée (SC) dans le bras',
        'home.rrDoses': '2 doses (RR1, RR2)',
        'home.rrAge': '9 mois, 18 mois',
        'home.rrSideEffects': 'Légère fièvre et éruption cutanée bénigne 5-12 jours après, disparaît spontanément',
        'home.vpiDisease': 'Poliomyélite (dose de renforcement injectable)',
        'home.vpiRoute': 'Injection intramusculaire (IM) ou sous-cutanée',
        'home.vpiDoses': '2 doses (VPI1, VPI2)',
        'home.vpiAge': '12 semaines, 9 mois',
        'home.vpiSideEffects': "Légère rougeur au site d'injection, disparaît en deux jours",
        'home.hbDisease': 'Hépatite virale B',
        'home.hbRoute': 'Injection intramusculaire (IM)',
        'home.hbDoses': 'Une dose à la naissance si disponible (HBn) ou durant les 4 premières semaines si elle n’a pas été administrée à la naissance (HB1)',
        'home.hbAge': 'À la naissance ou durant les 4 premières semaines selon le cas',
        'home.hbSideEffects': "Légère douleur au site d'injection, fièvre légère rare",
        'home.hpvDisease': "Papillomavirus humain (cancer du col de l'utérus)",
        'home.hpvRoute': 'Injection intramusculaire (IM) dans le bras',
        'home.hpvDoses': '2 doses (HPV)',
        'home.hpvAge': '11 ans (filles)',
        'home.hpvSideEffects': "Douleur et gonflement au site d'injection, légère sensation de vertige, disparaît en 1-2 jours",
        'auth.loginTitle': 'Connexion',
        'auth.loginIntro': 'Saisissez vos informations pour accéder au suivi vaccinal.',
        'auth.nationalId': 'Numéro de la carte nationale',
        'auth.password': 'Mot de passe',
        'auth.nationalIdPlaceholder': 'Exemple : AB123456',
        'auth.passwordPlaceholder': 'Saisissez le mot de passe',
        'auth.loginButton': 'Se connecter',
        'auth.registerTitle': 'Créer un nouveau compte',
        'auth.registerIntro': 'Renseignez les informations de base pour lier le parent au dossier vaccinal.',
        'auth.fullName': 'Nom complet',
        'auth.gender': 'Sexe',
        'auth.selectGender': 'Choisir le sexe',
        'auth.dateOfBirth': 'Date de naissance',
        'auth.address': 'Adresse',
        'auth.phoneNumber': 'Téléphone',
        'auth.registerButton': 'Créer le compte',
        'auth.profileTitle': 'Profil',
        'auth.profileLoginRequired': 'Veuillez vous connecter pour afficher le profil.',
        'auth.saveChanges': 'Enregistrer les modifications',
        'children.pageTitle': 'Gestion des informations des enfants',
        'children.listTitle': 'Enfants enregistrés',
        'children.empty': 'Aucun enfant enregistré.',
        'children.addButton': 'Ajouter un enfant',
        'children.cancel': 'Annuler',
        'children.closeModal': 'Fermer',
        'children.actions': 'Actions',
        'children.edit': 'Modifier',
        'children.delete': 'Supprimer',
        'children.save': 'Enregistrer',
        'children.deleteConfirm': 'Voulez-vous supprimer les informations de cet enfant ?',
        'children.gender': 'Sexe',
        'children.birthDate': 'Date de naissance',
        'children.nationalId': 'Carte nationale',
        'children.address': 'Adresse',
        'children.phone': 'Téléphone',
        'appointments.pageTitle': 'Rendez-vous de vaccination',
        'appointments.welcome': 'Bienvenue, {{name}}',
        'appointments.calendarTitle': 'Rendez-vous des doses des enfants',
        'appointments.monthView': 'La liste affiche les doses du mois {{month}}',
        'appointments.dayView': 'La liste affiche les doses du jour {{day}}',
        'appointments.backToMonth': 'Afficher les vaccinations de ce mois',
        'appointments.listTitleDefault': 'Rendez-vous prévus et enregistrés',
        'appointments.listTitleDay': 'Doses du jour {{day}}',
        'appointments.listTitleMonth': 'Vaccinations du mois {{month}}',
        'appointments.emptyDefault': 'Aucun rendez-vous disponible pour le moment.',
        'appointments.emptyDay': 'Aucune dose pour ce jour.',
        'appointments.emptyMonth': 'Aucune dose prévue ou enregistrée ce mois-ci.',
        'appointments.loading': 'Chargement des rendez-vous...',
        'appointments.error': 'Impossible de charger les rendez-vous : {{error}}',
        'appointments.date': 'Date du rendez-vous',
        'appointments.time': 'Heure',
        'appointments.vaccine': 'Vaccin',
        'appointments.status': 'Statut',
        'appointments.type': 'Type',
        'appointments.note': 'Note',
        'appointments.typeExpected': 'Rendez-vous prévu',
        'appointments.typeSaved': 'Rendez-vous enregistré',
        'appointments.statusOverdue': 'En retard',
        'appointments.statusToday': "Aujourd'hui",
        'appointments.statusScheduled': 'Planifié',
        'dashboard.appointments': 'Vos rendez-vous',
        'dashboard.children': 'Vos enfants',
        'vaccine.eyebrow': 'Calendrier PNI',
        'vaccine.title': 'Liste des doses et dates prévues',
        'vaccine.text': "Ce tableau suit la liste des antigènes fournie et la logique des dates visible sur votre image. L'exemple par défaut correspond à un enfant né le 01/01/1998.",
        'vaccine.selectChild': 'Choisir un enfant enregistré',
        'vaccine.manual': 'Saisie manuelle',
        'vaccine.birthDate': 'Date de naissance',
        'vaccine.selectedSummary': 'Enfant sélectionné : {{name}}, date de naissance : {{date}}',
        'vaccine.manualSummary': 'Date utilisée pour le calcul : {{date}}',
        'vaccine.completed': 'Doses réalisées',
        'vaccine.catchup': 'Rattrapage vaccinal',
        'vaccine.pending': 'Rendez-vous en attente',
        'vaccine.loading': 'Chargement des enfants enregistrés...',
        'vaccine.table.order': 'Ordre',
        'vaccine.table.age': 'Âge de référence',
        'vaccine.table.antigen': 'Antigène',
        'vaccine.table.scheduledDate': 'Date prévue',
        'vaccine.table.completedDate': 'Date de dose réalisée',
        'vaccine.table.catchup': 'Rattrapage vaccinal',
        'vaccine.table.relaunch': 'Relance',
        'vaccine.table.note': 'Note',
        'vaccine.yes': 'Oui',
        'vaccine.no': 'Non',
        'vaccine.notRequired': 'Non requise',
        'vaccine.inRelaunch': 'En situation de relance',
        'vaccine.underTracking': 'En suivi',
        'gender.male': 'Garçon',
        'gender.female': 'Fille'
    }
};

const AppPreferencesContext = createContext<AppPreferencesContextType | undefined>(undefined);

const formatTranslation = (template: string, params?: TranslationParams) => {
    if (!params) {
        return template;
    }

    return Object.entries(params).reduce((accumulator, [key, value]) => {
        return accumulator.replace(new RegExp(`{{${key}}}`, 'g'), String(value));
    }, template);
};

export const AppPreferencesProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('app-language') as Language) || 'ar');
    const [theme, setTheme] = useState<ThemeMode>(() => (localStorage.getItem('app-theme') as ThemeMode) || 'light');

    useEffect(() => {
        localStorage.setItem('app-language', language);
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
        document.body.dir = language === 'ar' ? 'rtl' : 'ltr';
    }, [language]);

    useEffect(() => {
        localStorage.setItem('app-theme', theme);
        document.body.dataset.theme = theme;
    }, [theme]);

    const value = useMemo<AppPreferencesContextType>(() => ({
        language,
        theme,
        isRtl: language === 'ar',
        setLanguage,
        toggleLanguage: () => setLanguage((currentValue) => (currentValue === 'ar' ? 'fr' : 'ar')),
        toggleTheme: () => setTheme((currentValue) => (currentValue === 'light' ? 'dark' : 'light')),
        t: (key: string, params?: TranslationParams) => {
            const translation = translations[language][key] || key;
            return formatTranslation(translation, params);
        }
    }), [language, theme]);

    return <AppPreferencesContext.Provider value={value}>{children}</AppPreferencesContext.Provider>;
};

export const useAppPreferences = () => {
    const context = useContext(AppPreferencesContext);

    if (!context) {
        throw new Error('useAppPreferences must be used within AppPreferencesProvider');
    }

    return context;
};
